export const SAT_TABLE_CLASS = [
  "w-full border-separate border-spacing-0 text-[12.5px]",
  "[&_thead_th]:bg-[var(--bg-1)] [&_thead_th]:border-b [&_thead_th]:border-[var(--line)]",
  "[&_thead_th]:px-[14px] [&_thead_th]:py-[11px] [&_thead_th]:text-left",
  "[&_thead_th]:text-[10.5px] [&_thead_th]:font-semibold [&_thead_th]:uppercase",
  "[&_thead_th]:tracking-[0.10em] [&_thead_th]:text-[var(--fg-2)]",
  "[&_thead_th.num]:text-right",
  "[&_tbody_td]:px-[14px] [&_tbody_td]:py-[10px] [&_tbody_td]:border-b",
  "[&_tbody_td]:border-[color-mix(in_oklch,var(--line),transparent_45%)]",
  "[&_tbody_td]:font-['Geist_Mono',monospace] [&_tbody_td]:text-[12.5px]",
  "[&_tbody_td]:text-[var(--fg-1)] [&_tbody_td]:align-middle",
  "[&_tbody_tr]:cursor-pointer",
  "[&_tbody_tr:hover_td]:bg-[var(--bg-row-h,var(--bg-2))]",
  "[&_tbody_tr.is-warn_td]:bg-[color-mix(in_oklch,var(--color-warning),transparent_94%)]",
  "[&_tbody_tr.is-err_td]:bg-[color-mix(in_oklch,var(--color-error),transparent_94%)]",
  "[&_tbody_td.num]:text-right [&_tbody_td.num]:text-[var(--fg-0)]",
  "[&_tbody_td.strong]:text-[var(--fg-0)]",
  "[&_tbody_td.dim]:text-[var(--fg-2)]",
  "[&_tbody_td:first-child]:pl-4",
  "[&_tbody_td:last-child]:pr-4",
].join(" ");
