export const ROUTES = {
  login: "/login",
  signup: "/signup",
  welcome: "/welcome",
  device: "/device",
  home: "/",
  features: "/features",
  architecture: "/architecture",
  pricing: "/pricing",
  opentelemetry: "/opentelemetry",
  selfHost: "/self-host",
  privacy: "/privacy",
  terms: "/terms",
  security: "/security",
  overview: "/overview",
  services: "/services",
  serviceMap: "/service-map",
  serviceDetail: "/services/$serviceName",
  logs: "/logs",
  traces: "/traces",
  traceDetail: "/traces/$traceId",
  llm: "/llm",
  traceCompare: "/traces/compare",
  metrics: "/metrics",
  infrastructure: "/infrastructure",
  hosts: "/infrastructure/hosts",
  hostDetail: "/infrastructure/hosts/$host",
  containerDetail: "/infrastructure/containers/$container",
  errors: "/errors",
  errorGroupDetail: "/errors/$groupId",
  saturation: "/saturation",
  saturationDatabase: "/saturation/database",
  saturationDatabaseDetail: "/saturation/database/instance/$system",
  saturationDatabaseQuery: "/saturation/database/query/$queryId",
  saturationKafkaOverview: "/saturation/kafka",

  ingestion: "/ingestion",

  monitors: "/monitors",
  monitorsNew: "/monitors/new",
  monitorDetail: "/monitors/$monitorId",
  monitorEdit: "/monitors/$monitorId/edit",
  monitorsNotifications: "/monitors/notifications",
  alertsNew: "/alerts/new",

  dashboards: "/dashboards",
  dashboardDetail: "/dashboards/$pageId",

  settings: "/settings",
} as const;

export type AppRoutePath = (typeof ROUTES)[keyof typeof ROUTES];
