/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProductRouteImport } from './routes/product'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppMetricsRouteImport } from './routes/_app/metrics'
import { Route as AppTracesIndexRouteImport } from './routes/_app/traces/index'
import { Route as AppServicesIndexRouteImport } from './routes/_app/services/index'
import { Route as AppLogsIndexRouteImport } from './routes/_app/logs/index'
import { Route as AppLlmIndexRouteImport } from './routes/_app/llm/index'
import { Route as AppInfrastructureIndexRouteImport } from './routes/_app/infrastructure/index'
import { Route as AppErrorsIndexRouteImport } from './routes/_app/errors/index'
import { Route as AppDeploymentsIndexRouteImport } from './routes/_app/deployments/index'
import { Route as AppDatabaseIndexRouteImport } from './routes/_app/database/index'
import { Route as AppTracesTraceIdRouteImport } from './routes/_app/traces/$traceId'
import { Route as AppServicesMapRouteImport } from './routes/_app/services/map'
import { Route as AppServicesServiceNameRouteImport } from './routes/_app/services/$serviceName'
import { Route as AppLogsTransactionsRouteImport } from './routes/_app/logs/transactions'
import { Route as AppLogsPatternsRouteImport } from './routes/_app/logs/patterns'
import { Route as AppDatabaseQueriesRouteImport } from './routes/_app/database/queries'
import { Route as AppAlertsNewRouteImport } from './routes/_app/alerts.new'
import { Route as AppSaturationDatabaseIndexRouteImport } from './routes/_app/saturation/database/index'
import { Route as AppInfrastructureHostsHostRouteImport } from './routes/_app/infrastructure/hosts/$host'
import { Route as AppInfrastructureContainersContainerRouteImport } from './routes/_app/infrastructure/containers/$container'
import { Route as AppDeploymentsServiceVersionRouteImport } from './routes/_app/deployments/$service.$version'
import { Route as AppDatabaseQueryQueryIdRouteImport } from './routes/_app/database/query/$queryId'
import { Route as AppDatabaseInstanceSystemRouteImport } from './routes/_app/database/instance/$system'
import { Route as AppSaturationDatabaseQueryQueryIdRouteImport } from './routes/_app/saturation/database/query/$queryId'
import { Route as AppSaturationDatabaseInstanceSystemRouteImport } from './routes/_app/saturation/database/instance/$system'

const AppOverviewLazyRouteImport = createFileRoute('/_app/overview')()
const AppDeviceLazyRouteImport = createFileRoute('/_app/device')()
const AppCloudLazyRouteImport = createFileRoute('/_app/cloud')()
const AppSaturationIndexLazyRouteImport = createFileRoute('/_app/saturation/')()
const AppMonitorsIndexLazyRouteImport = createFileRoute('/_app/monitors/')()
const AppDashboardsIndexLazyRouteImport = createFileRoute('/_app/dashboards/')()
const AppSaturationKafkaLazyRouteImport = createFileRoute(
  '/_app/saturation/kafka',
)()
const AppMonitorsNotificationsLazyRouteImport = createFileRoute(
  '/_app/monitors/notifications',
)()
const AppMonitorsNewLazyRouteImport = createFileRoute('/_app/monitors/new')()
const AppMonitorsMonitorIdLazyRouteImport = createFileRoute(
  '/_app/monitors/$monitorId',
)()
const AppErrorsGroupIdLazyRouteImport = createFileRoute(
  '/_app/errors/$groupId',
)()
const AppDashboardsPageIdLazyRouteImport = createFileRoute(
  '/_app/dashboards/$pageId',
)()
const AppMonitorsMonitorIdEditLazyRouteImport = createFileRoute(
  '/_app/monitors/$monitorId/edit',
)()
const AppLlmTracesTraceIdLazyRouteImport = createFileRoute(
  '/_app/llm/traces/$traceId',
)()
const AppLlmSessionsSessionIdLazyRouteImport = createFileRoute(
  '/_app/llm/sessions/$sessionId',
)()
const AppLlmPromptsNameLazyRouteImport = createFileRoute(
  '/_app/llm/prompts/$name',
)()
const AppLlmDatasetsDatasetIdLazyRouteImport = createFileRoute(
  '/_app/llm/datasets/$datasetId',
)()

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/welcome.lazy').then((d) => d.Route))
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/reset-password.lazy').then((d) => d.Route),
)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/forgot-password.lazy').then((d) => d.Route),
)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOverviewLazyRoute = AppOverviewLazyRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/overview.lazy').then((d) => d.Route))
const AppDeviceLazyRoute = AppDeviceLazyRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/device.lazy').then((d) => d.Route))
const AppCloudLazyRoute = AppCloudLazyRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/cloud.lazy').then((d) => d.Route))
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/settings.lazy').then((d) => d.Route))
const AppMetricsRoute = AppMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/metrics.lazy').then((d) => d.Route))
const AppSaturationIndexLazyRoute = AppSaturationIndexLazyRouteImport.update({
  id: '/saturation/',
  path: '/saturation/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/saturation/index.lazy').then((d) => d.Route),
)
const AppMonitorsIndexLazyRoute = AppMonitorsIndexLazyRouteImport.update({
  id: '/monitors/',
  path: '/monitors/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/monitors/index.lazy').then((d) => d.Route),
)
const AppDashboardsIndexLazyRoute = AppDashboardsIndexLazyRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/dashboards/index.lazy').then((d) => d.Route),
)
const AppTracesIndexRoute = AppTracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/traces/index.lazy').then((d) => d.Route),
)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/services/index.lazy').then((d) => d.Route),
)
const AppLogsIndexRoute = AppLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/logs/index.lazy').then((d) => d.Route),
)
const AppLlmIndexRoute = AppLlmIndexRouteImport.update({
  id: '/llm/',
  path: '/llm/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/llm/index.lazy').then((d) => d.Route),
)
const AppInfrastructureIndexRoute = AppInfrastructureIndexRouteImport.update({
  id: '/infrastructure/',
  path: '/infrastructure/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/infrastructure/index.lazy').then((d) => d.Route),
)
const AppErrorsIndexRoute = AppErrorsIndexRouteImport.update({
  id: '/errors/',
  path: '/errors/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/errors/index.lazy').then((d) => d.Route),
)
const AppDeploymentsIndexRoute = AppDeploymentsIndexRouteImport.update({
  id: '/deployments/',
  path: '/deployments/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/deployments/index.lazy').then((d) => d.Route),
)
const AppDatabaseIndexRoute = AppDatabaseIndexRouteImport.update({
  id: '/database/',
  path: '/database/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/database/index.lazy').then((d) => d.Route),
)
const AppSaturationKafkaLazyRoute = AppSaturationKafkaLazyRouteImport.update({
  id: '/saturation/kafka',
  path: '/saturation/kafka',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/saturation/kafka.lazy').then((d) => d.Route),
)
const AppMonitorsNotificationsLazyRoute =
  AppMonitorsNotificationsLazyRouteImport.update({
    id: '/monitors/notifications',
    path: '/monitors/notifications',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/monitors/notifications.lazy').then((d) => d.Route),
  )
const AppMonitorsNewLazyRoute = AppMonitorsNewLazyRouteImport.update({
  id: '/monitors/new',
  path: '/monitors/new',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/monitors/new.lazy').then((d) => d.Route),
)
const AppMonitorsMonitorIdLazyRoute =
  AppMonitorsMonitorIdLazyRouteImport.update({
    id: '/monitors/$monitorId',
    path: '/monitors/$monitorId',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/monitors/$monitorId.lazy').then((d) => d.Route),
  )
const AppErrorsGroupIdLazyRoute = AppErrorsGroupIdLazyRouteImport.update({
  id: '/errors/$groupId',
  path: '/errors/$groupId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/errors/$groupId.lazy').then((d) => d.Route),
)
const AppDashboardsPageIdLazyRoute = AppDashboardsPageIdLazyRouteImport.update({
  id: '/dashboards/$pageId',
  path: '/dashboards/$pageId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/dashboards/$pageId.lazy').then((d) => d.Route),
)
const AppTracesTraceIdRoute = AppTracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/traces/$traceId.lazy').then((d) => d.Route),
)
const AppServicesMapRoute = AppServicesMapRouteImport.update({
  id: '/services/map',
  path: '/services/map',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesServiceNameRoute = AppServicesServiceNameRouteImport.update({
  id: '/services/$serviceName',
  path: '/services/$serviceName',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/services/$serviceName.lazy').then((d) => d.Route),
)
const AppLogsTransactionsRoute = AppLogsTransactionsRouteImport.update({
  id: '/logs/transactions',
  path: '/logs/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsPatternsRoute = AppLogsPatternsRouteImport.update({
  id: '/logs/patterns',
  path: '/logs/patterns',
  getParentRoute: () => AppRoute,
} as any)
const AppDatabaseQueriesRoute = AppDatabaseQueriesRouteImport.update({
  id: '/database/queries',
  path: '/database/queries',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/database/queries.lazy').then((d) => d.Route),
)
const AppAlertsNewRoute = AppAlertsNewRouteImport.update({
  id: '/alerts/new',
  path: '/alerts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSaturationDatabaseIndexRoute =
  AppSaturationDatabaseIndexRouteImport.update({
    id: '/saturation/database/',
    path: '/saturation/database/',
    getParentRoute: () => AppRoute,
  } as any)
const AppMonitorsMonitorIdEditLazyRoute =
  AppMonitorsMonitorIdEditLazyRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppMonitorsMonitorIdLazyRoute,
  } as any).lazy(() =>
    import('./routes/_app/monitors/$monitorId/edit.lazy').then((d) => d.Route),
  )
const AppLlmTracesTraceIdLazyRoute = AppLlmTracesTraceIdLazyRouteImport.update({
  id: '/llm/traces/$traceId',
  path: '/llm/traces/$traceId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/llm/traces/$traceId.lazy').then((d) => d.Route),
)
const AppLlmSessionsSessionIdLazyRoute =
  AppLlmSessionsSessionIdLazyRouteImport.update({
    id: '/llm/sessions/$sessionId',
    path: '/llm/sessions/$sessionId',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/llm/sessions/$sessionId.lazy').then((d) => d.Route),
  )
const AppLlmPromptsNameLazyRoute = AppLlmPromptsNameLazyRouteImport.update({
  id: '/llm/prompts/$name',
  path: '/llm/prompts/$name',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/llm/prompts/$name.lazy').then((d) => d.Route),
)
const AppLlmDatasetsDatasetIdLazyRoute =
  AppLlmDatasetsDatasetIdLazyRouteImport.update({
    id: '/llm/datasets/$datasetId',
    path: '/llm/datasets/$datasetId',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/llm/datasets/$datasetId.lazy').then((d) => d.Route),
  )
const AppInfrastructureHostsHostRoute =
  AppInfrastructureHostsHostRouteImport.update({
    id: '/infrastructure/hosts/$host',
    path: '/infrastructure/hosts/$host',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/infrastructure/hosts/$host.lazy').then(
      (d) => d.Route,
    ),
  )
const AppInfrastructureContainersContainerRoute =
  AppInfrastructureContainersContainerRouteImport.update({
    id: '/infrastructure/containers/$container',
    path: '/infrastructure/containers/$container',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/infrastructure/containers/$container.lazy').then(
      (d) => d.Route,
    ),
  )
const AppDeploymentsServiceVersionRoute =
  AppDeploymentsServiceVersionRouteImport.update({
    id: '/deployments/$service/$version',
    path: '/deployments/$service/$version',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/deployments/$service.$version.lazy').then(
      (d) => d.Route,
    ),
  )
const AppDatabaseQueryQueryIdRoute = AppDatabaseQueryQueryIdRouteImport.update({
  id: '/database/query/$queryId',
  path: '/database/query/$queryId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/database/query/$queryId.lazy').then((d) => d.Route),
)
const AppDatabaseInstanceSystemRoute =
  AppDatabaseInstanceSystemRouteImport.update({
    id: '/database/instance/$system',
    path: '/database/instance/$system',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/database/instance/$system.lazy').then((d) => d.Route),
  )
const AppSaturationDatabaseQueryQueryIdRoute =
  AppSaturationDatabaseQueryQueryIdRouteImport.update({
    id: '/saturation/database/query/$queryId',
    path: '/saturation/database/query/$queryId',
    getParentRoute: () => AppRoute,
  } as any)
const AppSaturationDatabaseInstanceSystemRoute =
  AppSaturationDatabaseInstanceSystemRouteImport.update({
    id: '/saturation/database/instance/$system',
    path: '/saturation/database/instance/$system',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/metrics': typeof AppMetricsRoute
  '/settings': typeof AppSettingsRoute
  '/cloud': typeof AppCloudLazyRoute
  '/device': typeof AppDeviceLazyRoute
  '/overview': typeof AppOverviewLazyRoute
  '/alerts/new': typeof AppAlertsNewRoute
  '/database/queries': typeof AppDatabaseQueriesRoute
  '/logs/patterns': typeof AppLogsPatternsRoute
  '/logs/transactions': typeof AppLogsTransactionsRoute
  '/services/$serviceName': typeof AppServicesServiceNameRoute
  '/services/map': typeof AppServicesMapRoute
  '/traces/$traceId': typeof AppTracesTraceIdRoute
  '/dashboards/$pageId': typeof AppDashboardsPageIdLazyRoute
  '/errors/$groupId': typeof AppErrorsGroupIdLazyRoute
  '/monitors/$monitorId': typeof AppMonitorsMonitorIdLazyRouteWithChildren
  '/monitors/new': typeof AppMonitorsNewLazyRoute
  '/monitors/notifications': typeof AppMonitorsNotificationsLazyRoute
  '/saturation/kafka': typeof AppSaturationKafkaLazyRoute
  '/database/': typeof AppDatabaseIndexRoute
  '/deployments/': typeof AppDeploymentsIndexRoute
  '/errors/': typeof AppErrorsIndexRoute
  '/infrastructure/': typeof AppInfrastructureIndexRoute
  '/llm/': typeof AppLlmIndexRoute
  '/logs/': typeof AppLogsIndexRoute
  '/services/': typeof AppServicesIndexRoute
  '/traces/': typeof AppTracesIndexRoute
  '/dashboards/': typeof AppDashboardsIndexLazyRoute
  '/monitors/': typeof AppMonitorsIndexLazyRoute
  '/saturation/': typeof AppSaturationIndexLazyRoute
  '/database/instance/$system': typeof AppDatabaseInstanceSystemRoute
  '/database/query/$queryId': typeof AppDatabaseQueryQueryIdRoute
  '/deployments/$service/$version': typeof AppDeploymentsServiceVersionRoute
  '/infrastructure/containers/$container': typeof AppInfrastructureContainersContainerRoute
  '/infrastructure/hosts/$host': typeof AppInfrastructureHostsHostRoute
  '/llm/datasets/$datasetId': typeof AppLlmDatasetsDatasetIdLazyRoute
  '/llm/prompts/$name': typeof AppLlmPromptsNameLazyRoute
  '/llm/sessions/$sessionId': typeof AppLlmSessionsSessionIdLazyRoute
  '/llm/traces/$traceId': typeof AppLlmTracesTraceIdLazyRoute
  '/monitors/$monitorId/edit': typeof AppMonitorsMonitorIdEditLazyRoute
  '/saturation/database/': typeof AppSaturationDatabaseIndexRoute
  '/saturation/database/instance/$system': typeof AppSaturationDatabaseInstanceSystemRoute
  '/saturation/database/query/$queryId': typeof AppSaturationDatabaseQueryQueryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/metrics': typeof AppMetricsRoute
  '/settings': typeof AppSettingsRoute
  '/cloud': typeof AppCloudLazyRoute
  '/device': typeof AppDeviceLazyRoute
  '/overview': typeof AppOverviewLazyRoute
  '/alerts/new': typeof AppAlertsNewRoute
  '/database/queries': typeof AppDatabaseQueriesRoute
  '/logs/patterns': typeof AppLogsPatternsRoute
  '/logs/transactions': typeof AppLogsTransactionsRoute
  '/services/$serviceName': typeof AppServicesServiceNameRoute
  '/services/map': typeof AppServicesMapRoute
  '/traces/$traceId': typeof AppTracesTraceIdRoute
  '/dashboards/$pageId': typeof AppDashboardsPageIdLazyRoute
  '/errors/$groupId': typeof AppErrorsGroupIdLazyRoute
  '/monitors/$monitorId': typeof AppMonitorsMonitorIdLazyRouteWithChildren
  '/monitors/new': typeof AppMonitorsNewLazyRoute
  '/monitors/notifications': typeof AppMonitorsNotificationsLazyRoute
  '/saturation/kafka': typeof AppSaturationKafkaLazyRoute
  '/database': typeof AppDatabaseIndexRoute
  '/deployments': typeof AppDeploymentsIndexRoute
  '/errors': typeof AppErrorsIndexRoute
  '/infrastructure': typeof AppInfrastructureIndexRoute
  '/llm': typeof AppLlmIndexRoute
  '/logs': typeof AppLogsIndexRoute
  '/services': typeof AppServicesIndexRoute
  '/traces': typeof AppTracesIndexRoute
  '/dashboards': typeof AppDashboardsIndexLazyRoute
  '/monitors': typeof AppMonitorsIndexLazyRoute
  '/saturation': typeof AppSaturationIndexLazyRoute
  '/database/instance/$system': typeof AppDatabaseInstanceSystemRoute
  '/database/query/$queryId': typeof AppDatabaseQueryQueryIdRoute
  '/deployments/$service/$version': typeof AppDeploymentsServiceVersionRoute
  '/infrastructure/containers/$container': typeof AppInfrastructureContainersContainerRoute
  '/infrastructure/hosts/$host': typeof AppInfrastructureHostsHostRoute
  '/llm/datasets/$datasetId': typeof AppLlmDatasetsDatasetIdLazyRoute
  '/llm/prompts/$name': typeof AppLlmPromptsNameLazyRoute
  '/llm/sessions/$sessionId': typeof AppLlmSessionsSessionIdLazyRoute
  '/llm/traces/$traceId': typeof AppLlmTracesTraceIdLazyRoute
  '/monitors/$monitorId/edit': typeof AppMonitorsMonitorIdEditLazyRoute
  '/saturation/database': typeof AppSaturationDatabaseIndexRoute
  '/saturation/database/instance/$system': typeof AppSaturationDatabaseInstanceSystemRoute
  '/saturation/database/query/$queryId': typeof AppSaturationDatabaseQueryQueryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/_app/metrics': typeof AppMetricsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/cloud': typeof AppCloudLazyRoute
  '/_app/device': typeof AppDeviceLazyRoute
  '/_app/overview': typeof AppOverviewLazyRoute
  '/_app/alerts/new': typeof AppAlertsNewRoute
  '/_app/database/queries': typeof AppDatabaseQueriesRoute
  '/_app/logs/patterns': typeof AppLogsPatternsRoute
  '/_app/logs/transactions': typeof AppLogsTransactionsRoute
  '/_app/services/$serviceName': typeof AppServicesServiceNameRoute
  '/_app/services/map': typeof AppServicesMapRoute
  '/_app/traces/$traceId': typeof AppTracesTraceIdRoute
  '/_app/dashboards/$pageId': typeof AppDashboardsPageIdLazyRoute
  '/_app/errors/$groupId': typeof AppErrorsGroupIdLazyRoute
  '/_app/monitors/$monitorId': typeof AppMonitorsMonitorIdLazyRouteWithChildren
  '/_app/monitors/new': typeof AppMonitorsNewLazyRoute
  '/_app/monitors/notifications': typeof AppMonitorsNotificationsLazyRoute
  '/_app/saturation/kafka': typeof AppSaturationKafkaLazyRoute
  '/_app/database/': typeof AppDatabaseIndexRoute
  '/_app/deployments/': typeof AppDeploymentsIndexRoute
  '/_app/errors/': typeof AppErrorsIndexRoute
  '/_app/infrastructure/': typeof AppInfrastructureIndexRoute
  '/_app/llm/': typeof AppLlmIndexRoute
  '/_app/logs/': typeof AppLogsIndexRoute
  '/_app/services/': typeof AppServicesIndexRoute
  '/_app/traces/': typeof AppTracesIndexRoute
  '/_app/dashboards/': typeof AppDashboardsIndexLazyRoute
  '/_app/monitors/': typeof AppMonitorsIndexLazyRoute
  '/_app/saturation/': typeof AppSaturationIndexLazyRoute
  '/_app/database/instance/$system': typeof AppDatabaseInstanceSystemRoute
  '/_app/database/query/$queryId': typeof AppDatabaseQueryQueryIdRoute
  '/_app/deployments/$service/$version': typeof AppDeploymentsServiceVersionRoute
  '/_app/infrastructure/containers/$container': typeof AppInfrastructureContainersContainerRoute
  '/_app/infrastructure/hosts/$host': typeof AppInfrastructureHostsHostRoute
  '/_app/llm/datasets/$datasetId': typeof AppLlmDatasetsDatasetIdLazyRoute
  '/_app/llm/prompts/$name': typeof AppLlmPromptsNameLazyRoute
  '/_app/llm/sessions/$sessionId': typeof AppLlmSessionsSessionIdLazyRoute
  '/_app/llm/traces/$traceId': typeof AppLlmTracesTraceIdLazyRoute
  '/_app/monitors/$monitorId/edit': typeof AppMonitorsMonitorIdEditLazyRoute
  '/_app/saturation/database/': typeof AppSaturationDatabaseIndexRoute
  '/_app/saturation/database/instance/$system': typeof AppSaturationDatabaseInstanceSystemRoute
  '/_app/saturation/database/query/$queryId': typeof AppSaturationDatabaseQueryQueryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/product'
    | '/reset-password'
    | '/signup'
    | '/welcome'
    | '/metrics'
    | '/settings'
    | '/cloud'
    | '/device'
    | '/overview'
    | '/alerts/new'
    | '/database/queries'
    | '/logs/patterns'
    | '/logs/transactions'
    | '/services/$serviceName'
    | '/services/map'
    | '/traces/$traceId'
    | '/dashboards/$pageId'
    | '/errors/$groupId'
    | '/monitors/$monitorId'
    | '/monitors/new'
    | '/monitors/notifications'
    | '/saturation/kafka'
    | '/database/'
    | '/deployments/'
    | '/errors/'
    | '/infrastructure/'
    | '/llm/'
    | '/logs/'
    | '/services/'
    | '/traces/'
    | '/dashboards/'
    | '/monitors/'
    | '/saturation/'
    | '/database/instance/$system'
    | '/database/query/$queryId'
    | '/deployments/$service/$version'
    | '/infrastructure/containers/$container'
    | '/infrastructure/hosts/$host'
    | '/llm/datasets/$datasetId'
    | '/llm/prompts/$name'
    | '/llm/sessions/$sessionId'
    | '/llm/traces/$traceId'
    | '/monitors/$monitorId/edit'
    | '/saturation/database/'
    | '/saturation/database/instance/$system'
    | '/saturation/database/query/$queryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/product'
    | '/reset-password'
    | '/signup'
    | '/welcome'
    | '/metrics'
    | '/settings'
    | '/cloud'
    | '/device'
    | '/overview'
    | '/alerts/new'
    | '/database/queries'
    | '/logs/patterns'
    | '/logs/transactions'
    | '/services/$serviceName'
    | '/services/map'
    | '/traces/$traceId'
    | '/dashboards/$pageId'
    | '/errors/$groupId'
    | '/monitors/$monitorId'
    | '/monitors/new'
    | '/monitors/notifications'
    | '/saturation/kafka'
    | '/database'
    | '/deployments'
    | '/errors'
    | '/infrastructure'
    | '/llm'
    | '/logs'
    | '/services'
    | '/traces'
    | '/dashboards'
    | '/monitors'
    | '/saturation'
    | '/database/instance/$system'
    | '/database/query/$queryId'
    | '/deployments/$service/$version'
    | '/infrastructure/containers/$container'
    | '/infrastructure/hosts/$host'
    | '/llm/datasets/$datasetId'
    | '/llm/prompts/$name'
    | '/llm/sessions/$sessionId'
    | '/llm/traces/$traceId'
    | '/monitors/$monitorId/edit'
    | '/saturation/database'
    | '/saturation/database/instance/$system'
    | '/saturation/database/query/$queryId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/product'
    | '/reset-password'
    | '/signup'
    | '/welcome'
    | '/_app/metrics'
    | '/_app/settings'
    | '/_app/cloud'
    | '/_app/device'
    | '/_app/overview'
    | '/_app/alerts/new'
    | '/_app/database/queries'
    | '/_app/logs/patterns'
    | '/_app/logs/transactions'
    | '/_app/services/$serviceName'
    | '/_app/services/map'
    | '/_app/traces/$traceId'
    | '/_app/dashboards/$pageId'
    | '/_app/errors/$groupId'
    | '/_app/monitors/$monitorId'
    | '/_app/monitors/new'
    | '/_app/monitors/notifications'
    | '/_app/saturation/kafka'
    | '/_app/database/'
    | '/_app/deployments/'
    | '/_app/errors/'
    | '/_app/infrastructure/'
    | '/_app/llm/'
    | '/_app/logs/'
    | '/_app/services/'
    | '/_app/traces/'
    | '/_app/dashboards/'
    | '/_app/monitors/'
    | '/_app/saturation/'
    | '/_app/database/instance/$system'
    | '/_app/database/query/$queryId'
    | '/_app/deployments/$service/$version'
    | '/_app/infrastructure/containers/$container'
    | '/_app/infrastructure/hosts/$host'
    | '/_app/llm/datasets/$datasetId'
    | '/_app/llm/prompts/$name'
    | '/_app/llm/sessions/$sessionId'
    | '/_app/llm/traces/$traceId'
    | '/_app/monitors/$monitorId/edit'
    | '/_app/saturation/database/'
    | '/_app/saturation/database/instance/$system'
    | '/_app/saturation/database/query/$queryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProductRoute: typeof ProductRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/device': {
      id: '/_app/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof AppDeviceLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cloud': {
      id: '/_app/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof AppCloudLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metrics': {
      id: '/_app/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AppMetricsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saturation/': {
      id: '/_app/saturation/'
      path: '/saturation'
      fullPath: '/saturation/'
      preLoaderRoute: typeof AppSaturationIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitors/': {
      id: '/_app/monitors/'
      path: '/monitors'
      fullPath: '/monitors/'
      preLoaderRoute: typeof AppMonitorsIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboards/': {
      id: '/_app/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof AppDashboardsIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/traces/': {
      id: '/_app/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof AppTracesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/': {
      id: '/_app/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs/': {
      id: '/_app/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof AppLogsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/llm/': {
      id: '/_app/llm/'
      path: '/llm'
      fullPath: '/llm/'
      preLoaderRoute: typeof AppLlmIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/infrastructure/': {
      id: '/_app/infrastructure/'
      path: '/infrastructure'
      fullPath: '/infrastructure/'
      preLoaderRoute: typeof AppInfrastructureIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/errors/': {
      id: '/_app/errors/'
      path: '/errors'
      fullPath: '/errors/'
      preLoaderRoute: typeof AppErrorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deployments/': {
      id: '/_app/deployments/'
      path: '/deployments'
      fullPath: '/deployments/'
      preLoaderRoute: typeof AppDeploymentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/database/': {
      id: '/_app/database/'
      path: '/database'
      fullPath: '/database/'
      preLoaderRoute: typeof AppDatabaseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saturation/kafka': {
      id: '/_app/saturation/kafka'
      path: '/saturation/kafka'
      fullPath: '/saturation/kafka'
      preLoaderRoute: typeof AppSaturationKafkaLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitors/notifications': {
      id: '/_app/monitors/notifications'
      path: '/monitors/notifications'
      fullPath: '/monitors/notifications'
      preLoaderRoute: typeof AppMonitorsNotificationsLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitors/new': {
      id: '/_app/monitors/new'
      path: '/monitors/new'
      fullPath: '/monitors/new'
      preLoaderRoute: typeof AppMonitorsNewLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitors/$monitorId': {
      id: '/_app/monitors/$monitorId'
      path: '/monitors/$monitorId'
      fullPath: '/monitors/$monitorId'
      preLoaderRoute: typeof AppMonitorsMonitorIdLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/errors/$groupId': {
      id: '/_app/errors/$groupId'
      path: '/errors/$groupId'
      fullPath: '/errors/$groupId'
      preLoaderRoute: typeof AppErrorsGroupIdLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboards/$pageId': {
      id: '/_app/dashboards/$pageId'
      path: '/dashboards/$pageId'
      fullPath: '/dashboards/$pageId'
      preLoaderRoute: typeof AppDashboardsPageIdLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/traces/$traceId': {
      id: '/_app/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof AppTracesTraceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/map': {
      id: '/_app/services/map'
      path: '/services/map'
      fullPath: '/services/map'
      preLoaderRoute: typeof AppServicesMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/$serviceName': {
      id: '/_app/services/$serviceName'
      path: '/services/$serviceName'
      fullPath: '/services/$serviceName'
      preLoaderRoute: typeof AppServicesServiceNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs/transactions': {
      id: '/_app/logs/transactions'
      path: '/logs/transactions'
      fullPath: '/logs/transactions'
      preLoaderRoute: typeof AppLogsTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs/patterns': {
      id: '/_app/logs/patterns'
      path: '/logs/patterns'
      fullPath: '/logs/patterns'
      preLoaderRoute: typeof AppLogsPatternsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/database/queries': {
      id: '/_app/database/queries'
      path: '/database/queries'
      fullPath: '/database/queries'
      preLoaderRoute: typeof AppDatabaseQueriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts/new': {
      id: '/_app/alerts/new'
      path: '/alerts/new'
      fullPath: '/alerts/new'
      preLoaderRoute: typeof AppAlertsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saturation/database/': {
      id: '/_app/saturation/database/'
      path: '/saturation/database'
      fullPath: '/saturation/database/'
      preLoaderRoute: typeof AppSaturationDatabaseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitors/$monitorId/edit': {
      id: '/_app/monitors/$monitorId/edit'
      path: '/edit'
      fullPath: '/monitors/$monitorId/edit'
      preLoaderRoute: typeof AppMonitorsMonitorIdEditLazyRouteImport
      parentRoute: typeof AppMonitorsMonitorIdLazyRoute
    }
    '/_app/llm/traces/$traceId': {
      id: '/_app/llm/traces/$traceId'
      path: '/llm/traces/$traceId'
      fullPath: '/llm/traces/$traceId'
      preLoaderRoute: typeof AppLlmTracesTraceIdLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/llm/sessions/$sessionId': {
      id: '/_app/llm/sessions/$sessionId'
      path: '/llm/sessions/$sessionId'
      fullPath: '/llm/sessions/$sessionId'
      preLoaderRoute: typeof AppLlmSessionsSessionIdLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/llm/prompts/$name': {
      id: '/_app/llm/prompts/$name'
      path: '/llm/prompts/$name'
      fullPath: '/llm/prompts/$name'
      preLoaderRoute: typeof AppLlmPromptsNameLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/llm/datasets/$datasetId': {
      id: '/_app/llm/datasets/$datasetId'
      path: '/llm/datasets/$datasetId'
      fullPath: '/llm/datasets/$datasetId'
      preLoaderRoute: typeof AppLlmDatasetsDatasetIdLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/infrastructure/hosts/$host': {
      id: '/_app/infrastructure/hosts/$host'
      path: '/infrastructure/hosts/$host'
      fullPath: '/infrastructure/hosts/$host'
      preLoaderRoute: typeof AppInfrastructureHostsHostRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/infrastructure/containers/$container': {
      id: '/_app/infrastructure/containers/$container'
      path: '/infrastructure/containers/$container'
      fullPath: '/infrastructure/containers/$container'
      preLoaderRoute: typeof AppInfrastructureContainersContainerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deployments/$service/$version': {
      id: '/_app/deployments/$service/$version'
      path: '/deployments/$service/$version'
      fullPath: '/deployments/$service/$version'
      preLoaderRoute: typeof AppDeploymentsServiceVersionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/database/query/$queryId': {
      id: '/_app/database/query/$queryId'
      path: '/database/query/$queryId'
      fullPath: '/database/query/$queryId'
      preLoaderRoute: typeof AppDatabaseQueryQueryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/database/instance/$system': {
      id: '/_app/database/instance/$system'
      path: '/database/instance/$system'
      fullPath: '/database/instance/$system'
      preLoaderRoute: typeof AppDatabaseInstanceSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saturation/database/query/$queryId': {
      id: '/_app/saturation/database/query/$queryId'
      path: '/saturation/database/query/$queryId'
      fullPath: '/saturation/database/query/$queryId'
      preLoaderRoute: typeof AppSaturationDatabaseQueryQueryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saturation/database/instance/$system': {
      id: '/_app/saturation/database/instance/$system'
      path: '/saturation/database/instance/$system'
      fullPath: '/saturation/database/instance/$system'
      preLoaderRoute: typeof AppSaturationDatabaseInstanceSystemRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppMonitorsMonitorIdLazyRouteChildren {
  AppMonitorsMonitorIdEditLazyRoute: typeof AppMonitorsMonitorIdEditLazyRoute
}

const AppMonitorsMonitorIdLazyRouteChildren: AppMonitorsMonitorIdLazyRouteChildren =
  {
    AppMonitorsMonitorIdEditLazyRoute: AppMonitorsMonitorIdEditLazyRoute,
  }

const AppMonitorsMonitorIdLazyRouteWithChildren =
  AppMonitorsMonitorIdLazyRoute._addFileChildren(
    AppMonitorsMonitorIdLazyRouteChildren,
  )

interface AppRouteChildren {
  AppMetricsRoute: typeof AppMetricsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppCloudLazyRoute: typeof AppCloudLazyRoute
  AppDeviceLazyRoute: typeof AppDeviceLazyRoute
  AppOverviewLazyRoute: typeof AppOverviewLazyRoute
  AppAlertsNewRoute: typeof AppAlertsNewRoute
  AppDatabaseQueriesRoute: typeof AppDatabaseQueriesRoute
  AppLogsPatternsRoute: typeof AppLogsPatternsRoute
  AppLogsTransactionsRoute: typeof AppLogsTransactionsRoute
  AppServicesServiceNameRoute: typeof AppServicesServiceNameRoute
  AppServicesMapRoute: typeof AppServicesMapRoute
  AppTracesTraceIdRoute: typeof AppTracesTraceIdRoute
  AppDashboardsPageIdLazyRoute: typeof AppDashboardsPageIdLazyRoute
  AppErrorsGroupIdLazyRoute: typeof AppErrorsGroupIdLazyRoute
  AppMonitorsMonitorIdLazyRoute: typeof AppMonitorsMonitorIdLazyRouteWithChildren
  AppMonitorsNewLazyRoute: typeof AppMonitorsNewLazyRoute
  AppMonitorsNotificationsLazyRoute: typeof AppMonitorsNotificationsLazyRoute
  AppSaturationKafkaLazyRoute: typeof AppSaturationKafkaLazyRoute
  AppDatabaseIndexRoute: typeof AppDatabaseIndexRoute
  AppDeploymentsIndexRoute: typeof AppDeploymentsIndexRoute
  AppErrorsIndexRoute: typeof AppErrorsIndexRoute
  AppInfrastructureIndexRoute: typeof AppInfrastructureIndexRoute
  AppLlmIndexRoute: typeof AppLlmIndexRoute
  AppLogsIndexRoute: typeof AppLogsIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppTracesIndexRoute: typeof AppTracesIndexRoute
  AppDashboardsIndexLazyRoute: typeof AppDashboardsIndexLazyRoute
  AppMonitorsIndexLazyRoute: typeof AppMonitorsIndexLazyRoute
  AppSaturationIndexLazyRoute: typeof AppSaturationIndexLazyRoute
  AppDatabaseInstanceSystemRoute: typeof AppDatabaseInstanceSystemRoute
  AppDatabaseQueryQueryIdRoute: typeof AppDatabaseQueryQueryIdRoute
  AppDeploymentsServiceVersionRoute: typeof AppDeploymentsServiceVersionRoute
  AppInfrastructureContainersContainerRoute: typeof AppInfrastructureContainersContainerRoute
  AppInfrastructureHostsHostRoute: typeof AppInfrastructureHostsHostRoute
  AppLlmDatasetsDatasetIdLazyRoute: typeof AppLlmDatasetsDatasetIdLazyRoute
  AppLlmPromptsNameLazyRoute: typeof AppLlmPromptsNameLazyRoute
  AppLlmSessionsSessionIdLazyRoute: typeof AppLlmSessionsSessionIdLazyRoute
  AppLlmTracesTraceIdLazyRoute: typeof AppLlmTracesTraceIdLazyRoute
  AppSaturationDatabaseIndexRoute: typeof AppSaturationDatabaseIndexRoute
  AppSaturationDatabaseInstanceSystemRoute: typeof AppSaturationDatabaseInstanceSystemRoute
  AppSaturationDatabaseQueryQueryIdRoute: typeof AppSaturationDatabaseQueryQueryIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMetricsRoute: AppMetricsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppCloudLazyRoute: AppCloudLazyRoute,
  AppDeviceLazyRoute: AppDeviceLazyRoute,
  AppOverviewLazyRoute: AppOverviewLazyRoute,
  AppAlertsNewRoute: AppAlertsNewRoute,
  AppDatabaseQueriesRoute: AppDatabaseQueriesRoute,
  AppLogsPatternsRoute: AppLogsPatternsRoute,
  AppLogsTransactionsRoute: AppLogsTransactionsRoute,
  AppServicesServiceNameRoute: AppServicesServiceNameRoute,
  AppServicesMapRoute: AppServicesMapRoute,
  AppTracesTraceIdRoute: AppTracesTraceIdRoute,
  AppDashboardsPageIdLazyRoute: AppDashboardsPageIdLazyRoute,
  AppErrorsGroupIdLazyRoute: AppErrorsGroupIdLazyRoute,
  AppMonitorsMonitorIdLazyRoute: AppMonitorsMonitorIdLazyRouteWithChildren,
  AppMonitorsNewLazyRoute: AppMonitorsNewLazyRoute,
  AppMonitorsNotificationsLazyRoute: AppMonitorsNotificationsLazyRoute,
  AppSaturationKafkaLazyRoute: AppSaturationKafkaLazyRoute,
  AppDatabaseIndexRoute: AppDatabaseIndexRoute,
  AppDeploymentsIndexRoute: AppDeploymentsIndexRoute,
  AppErrorsIndexRoute: AppErrorsIndexRoute,
  AppInfrastructureIndexRoute: AppInfrastructureIndexRoute,
  AppLlmIndexRoute: AppLlmIndexRoute,
  AppLogsIndexRoute: AppLogsIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppTracesIndexRoute: AppTracesIndexRoute,
  AppDashboardsIndexLazyRoute: AppDashboardsIndexLazyRoute,
  AppMonitorsIndexLazyRoute: AppMonitorsIndexLazyRoute,
  AppSaturationIndexLazyRoute: AppSaturationIndexLazyRoute,
  AppDatabaseInstanceSystemRoute: AppDatabaseInstanceSystemRoute,
  AppDatabaseQueryQueryIdRoute: AppDatabaseQueryQueryIdRoute,
  AppDeploymentsServiceVersionRoute: AppDeploymentsServiceVersionRoute,
  AppInfrastructureContainersContainerRoute:
    AppInfrastructureContainersContainerRoute,
  AppInfrastructureHostsHostRoute: AppInfrastructureHostsHostRoute,
  AppLlmDatasetsDatasetIdLazyRoute: AppLlmDatasetsDatasetIdLazyRoute,
  AppLlmPromptsNameLazyRoute: AppLlmPromptsNameLazyRoute,
  AppLlmSessionsSessionIdLazyRoute: AppLlmSessionsSessionIdLazyRoute,
  AppLlmTracesTraceIdLazyRoute: AppLlmTracesTraceIdLazyRoute,
  AppSaturationDatabaseIndexRoute: AppSaturationDatabaseIndexRoute,
  AppSaturationDatabaseInstanceSystemRoute:
    AppSaturationDatabaseInstanceSystemRoute,
  AppSaturationDatabaseQueryQueryIdRoute:
    AppSaturationDatabaseQueryQueryIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProductRoute: ProductRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
