/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProductRouteImport } from './routes/product'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIngestionRouteImport } from './routes/_app/ingestion'
import { Route as AppTracesTraceIdRouteImport } from './routes/_app/traces/$traceId'
import { Route as AppServicesMapRouteImport } from './routes/_app/services/map'
import { Route as AppLogsTransactionsRouteImport } from './routes/_app/logs/transactions'
import { Route as AppLogsPatternsRouteImport } from './routes/_app/logs/patterns'
import { Route as AppAlertsNewRouteImport } from './routes/_app/alerts.new'
import { Route as AppSaturationDatabaseQueryQueryIdRouteImport } from './routes/_app/saturation/database/query/$queryId'

const AppSettingsLazyRouteImport = createFileRoute('/_app/settings')()
const AppOverviewLazyRouteImport = createFileRoute('/_app/overview')()
const AppMetricsLazyRouteImport = createFileRoute('/_app/metrics')()
const AppLlmLazyRouteImport = createFileRoute('/_app/llm')()
const AppDeviceLazyRouteImport = createFileRoute('/_app/device')()
const AppCloudLazyRouteImport = createFileRoute('/_app/cloud')()
const AppTracesIndexLazyRouteImport = createFileRoute('/_app/traces/')()
const AppServicesIndexLazyRouteImport = createFileRoute('/_app/services/')()
const AppSaturationIndexLazyRouteImport = createFileRoute('/_app/saturation/')()
const AppMonitorsIndexLazyRouteImport = createFileRoute('/_app/monitors/')()
const AppLogsIndexLazyRouteImport = createFileRoute('/_app/logs/')()
const AppInfrastructureIndexLazyRouteImport = createFileRoute(
  '/_app/infrastructure/',
)()
const AppErrorsIndexLazyRouteImport = createFileRoute('/_app/errors/')()
const AppDashboardsIndexLazyRouteImport = createFileRoute('/_app/dashboards/')()
const AppServicesServiceNameLazyRouteImport = createFileRoute(
  '/_app/services/$serviceName',
)()
const AppSaturationKafkaLazyRouteImport = createFileRoute(
  '/_app/saturation/kafka',
)()
const AppMonitorsNotificationsLazyRouteImport = createFileRoute(
  '/_app/monitors/notifications',
)()
const AppMonitorsNewLazyRouteImport = createFileRoute('/_app/monitors/new')()
const AppMonitorsMonitorIdLazyRouteImport = createFileRoute(
  '/_app/monitors/$monitorId',
)()
const AppErrorsGroupIdLazyRouteImport = createFileRoute(
  '/_app/errors/$groupId',
)()
const AppDashboardsPageIdLazyRouteImport = createFileRoute(
  '/_app/dashboards/$pageId',
)()
const AppSaturationDatabaseIndexLazyRouteImport = createFileRoute(
  '/_app/saturation/database/',
)()
const AppMonitorsMonitorIdEditLazyRouteImport = createFileRoute(
  '/_app/monitors/$monitorId/edit',
)()
const AppInfrastructureHostsHostLazyRouteImport = createFileRoute(
  '/_app/infrastructure/hosts/$host',
)()
const AppInfrastructureContainersContainerLazyRouteImport = createFileRoute(
  '/_app/infrastructure/containers/$container',
)()
const AppSaturationDatabaseInstanceSystemLazyRouteImport = createFileRoute(
  '/_app/saturation/database/instance/$system',
)()

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/welcome.lazy').then((d) => d.Route))
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/signup.lazy').then((d) => d.Route))
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/reset-password.lazy').then((d) => d.Route),
)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/forgot-password.lazy').then((d) => d.Route),
)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsLazyRoute = AppSettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/settings.lazy').then((d) => d.Route))
const AppOverviewLazyRoute = AppOverviewLazyRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/overview.lazy').then((d) => d.Route))
const AppMetricsLazyRoute = AppMetricsLazyRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/metrics.lazy').then((d) => d.Route))
const AppLlmLazyRoute = AppLlmLazyRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/llm.lazy').then((d) => d.Route))
const AppDeviceLazyRoute = AppDeviceLazyRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/device.lazy').then((d) => d.Route))
const AppCloudLazyRoute = AppCloudLazyRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/cloud.lazy').then((d) => d.Route))
const AppIngestionRoute = AppIngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => AppRoute,
} as any)
const AppTracesIndexLazyRoute = AppTracesIndexLazyRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/traces/index.lazy').then((d) => d.Route),
)
const AppServicesIndexLazyRoute = AppServicesIndexLazyRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/services/index.lazy').then((d) => d.Route),
)
const AppSaturationIndexLazyRoute = AppSaturationIndexLazyRouteImport.update({
  id: '/saturation/',
  path: '/saturation/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/saturation/index.lazy').then((d) => d.Route),
)
const AppMonitorsIndexLazyRoute = AppMonitorsIndexLazyRouteImport.update({
  id: '/monitors/',
  path: '/monitors/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/monitors/index.lazy').then((d) => d.Route),
)
const AppLogsIndexLazyRoute = AppLogsIndexLazyRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/logs/index.lazy').then((d) => d.Route),
)
const AppInfrastructureIndexLazyRoute =
  AppInfrastructureIndexLazyRouteImport.update({
    id: '/infrastructure/',
    path: '/infrastructure/',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/infrastructure/index.lazy').then((d) => d.Route),
  )
const AppErrorsIndexLazyRoute = AppErrorsIndexLazyRouteImport.update({
  id: '/errors/',
  path: '/errors/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/errors/index.lazy').then((d) => d.Route),
)
const AppDashboardsIndexLazyRoute = AppDashboardsIndexLazyRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/dashboards/index.lazy').then((d) => d.Route),
)
const AppServicesServiceNameLazyRoute =
  AppServicesServiceNameLazyRouteImport.update({
    id: '/services/$serviceName',
    path: '/services/$serviceName',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/services/$serviceName.lazy').then((d) => d.Route),
  )
const AppSaturationKafkaLazyRoute = AppSaturationKafkaLazyRouteImport.update({
  id: '/saturation/kafka',
  path: '/saturation/kafka',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/saturation/kafka.lazy').then((d) => d.Route),
)
const AppMonitorsNotificationsLazyRoute =
  AppMonitorsNotificationsLazyRouteImport.update({
    id: '/monitors/notifications',
    path: '/monitors/notifications',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/monitors/notifications.lazy').then((d) => d.Route),
  )
const AppMonitorsNewLazyRoute = AppMonitorsNewLazyRouteImport.update({
  id: '/monitors/new',
  path: '/monitors/new',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/monitors/new.lazy').then((d) => d.Route),
)
const AppMonitorsMonitorIdLazyRoute =
  AppMonitorsMonitorIdLazyRouteImport.update({
    id: '/monitors/$monitorId',
    path: '/monitors/$monitorId',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/monitors/$monitorId.lazy').then((d) => d.Route),
  )
const AppErrorsGroupIdLazyRoute = AppErrorsGroupIdLazyRouteImport.update({
  id: '/errors/$groupId',
  path: '/errors/$groupId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/errors/$groupId.lazy').then((d) => d.Route),
)
const AppDashboardsPageIdLazyRoute = AppDashboardsPageIdLazyRouteImport.update({
  id: '/dashboards/$pageId',
  path: '/dashboards/$pageId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/dashboards/$pageId.lazy').then((d) => d.Route),
)
const AppTracesTraceIdRoute = AppTracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/traces/$traceId.lazy').then((d) => d.Route),
)
const AppServicesMapRoute = AppServicesMapRouteImport.update({
  id: '/services/map',
  path: '/services/map',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsTransactionsRoute = AppLogsTransactionsRouteImport.update({
  id: '/logs/transactions',
  path: '/logs/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsPatternsRoute = AppLogsPatternsRouteImport.update({
  id: '/logs/patterns',
  path: '/logs/patterns',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsNewRoute = AppAlertsNewRouteImport.update({
  id: '/alerts/new',
  path: '/alerts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSaturationDatabaseIndexLazyRoute =
  AppSaturationDatabaseIndexLazyRouteImport.update({
    id: '/saturation/database/',
    path: '/saturation/database/',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/saturation/database/index.lazy').then((d) => d.Route),
  )
const AppMonitorsMonitorIdEditLazyRoute =
  AppMonitorsMonitorIdEditLazyRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppMonitorsMonitorIdLazyRoute,
  } as any).lazy(() =>
    import('./routes/_app/monitors/$monitorId/edit.lazy').then((d) => d.Route),
  )
const AppInfrastructureHostsHostLazyRoute =
  AppInfrastructureHostsHostLazyRouteImport.update({
    id: '/infrastructure/hosts/$host',
    path: '/infrastructure/hosts/$host',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/infrastructure/hosts/$host.lazy').then(
      (d) => d.Route,
    ),
  )
const AppInfrastructureContainersContainerLazyRoute =
  AppInfrastructureContainersContainerLazyRouteImport.update({
    id: '/infrastructure/containers/$container',
    path: '/infrastructure/containers/$container',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/infrastructure/containers/$container.lazy').then(
      (d) => d.Route,
    ),
  )
const AppSaturationDatabaseInstanceSystemLazyRoute =
  AppSaturationDatabaseInstanceSystemLazyRouteImport.update({
    id: '/saturation/database/instance/$system',
    path: '/saturation/database/instance/$system',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/saturation/database/instance/$system.lazy').then(
      (d) => d.Route,
    ),
  )
const AppSaturationDatabaseQueryQueryIdRoute =
  AppSaturationDatabaseQueryQueryIdRouteImport.update({
    id: '/saturation/database/query/$queryId',
    path: '/saturation/database/query/$queryId',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/saturation/database/query/$queryId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/ingestion': typeof AppIngestionRoute
  '/cloud': typeof AppCloudLazyRoute
  '/device': typeof AppDeviceLazyRoute
  '/llm': typeof AppLlmLazyRoute
  '/metrics': typeof AppMetricsLazyRoute
  '/overview': typeof AppOverviewLazyRoute
  '/settings': typeof AppSettingsLazyRoute
  '/alerts/new': typeof AppAlertsNewRoute
  '/logs/patterns': typeof AppLogsPatternsRoute
  '/logs/transactions': typeof AppLogsTransactionsRoute
  '/services/map': typeof AppServicesMapRoute
  '/traces/$traceId': typeof AppTracesTraceIdRoute
  '/dashboards/$pageId': typeof AppDashboardsPageIdLazyRoute
  '/errors/$groupId': typeof AppErrorsGroupIdLazyRoute
  '/monitors/$monitorId': typeof AppMonitorsMonitorIdLazyRouteWithChildren
  '/monitors/new': typeof AppMonitorsNewLazyRoute
  '/monitors/notifications': typeof AppMonitorsNotificationsLazyRoute
  '/saturation/kafka': typeof AppSaturationKafkaLazyRoute
  '/services/$serviceName': typeof AppServicesServiceNameLazyRoute
  '/dashboards/': typeof AppDashboardsIndexLazyRoute
  '/errors/': typeof AppErrorsIndexLazyRoute
  '/infrastructure/': typeof AppInfrastructureIndexLazyRoute
  '/logs/': typeof AppLogsIndexLazyRoute
  '/monitors/': typeof AppMonitorsIndexLazyRoute
  '/saturation/': typeof AppSaturationIndexLazyRoute
  '/services/': typeof AppServicesIndexLazyRoute
  '/traces/': typeof AppTracesIndexLazyRoute
  '/infrastructure/containers/$container': typeof AppInfrastructureContainersContainerLazyRoute
  '/infrastructure/hosts/$host': typeof AppInfrastructureHostsHostLazyRoute
  '/monitors/$monitorId/edit': typeof AppMonitorsMonitorIdEditLazyRoute
  '/saturation/database/': typeof AppSaturationDatabaseIndexLazyRoute
  '/saturation/database/query/$queryId': typeof AppSaturationDatabaseQueryQueryIdRoute
  '/saturation/database/instance/$system': typeof AppSaturationDatabaseInstanceSystemLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/ingestion': typeof AppIngestionRoute
  '/cloud': typeof AppCloudLazyRoute
  '/device': typeof AppDeviceLazyRoute
  '/llm': typeof AppLlmLazyRoute
  '/metrics': typeof AppMetricsLazyRoute
  '/overview': typeof AppOverviewLazyRoute
  '/settings': typeof AppSettingsLazyRoute
  '/alerts/new': typeof AppAlertsNewRoute
  '/logs/patterns': typeof AppLogsPatternsRoute
  '/logs/transactions': typeof AppLogsTransactionsRoute
  '/services/map': typeof AppServicesMapRoute
  '/traces/$traceId': typeof AppTracesTraceIdRoute
  '/dashboards/$pageId': typeof AppDashboardsPageIdLazyRoute
  '/errors/$groupId': typeof AppErrorsGroupIdLazyRoute
  '/monitors/$monitorId': typeof AppMonitorsMonitorIdLazyRouteWithChildren
  '/monitors/new': typeof AppMonitorsNewLazyRoute
  '/monitors/notifications': typeof AppMonitorsNotificationsLazyRoute
  '/saturation/kafka': typeof AppSaturationKafkaLazyRoute
  '/services/$serviceName': typeof AppServicesServiceNameLazyRoute
  '/dashboards': typeof AppDashboardsIndexLazyRoute
  '/errors': typeof AppErrorsIndexLazyRoute
  '/infrastructure': typeof AppInfrastructureIndexLazyRoute
  '/logs': typeof AppLogsIndexLazyRoute
  '/monitors': typeof AppMonitorsIndexLazyRoute
  '/saturation': typeof AppSaturationIndexLazyRoute
  '/services': typeof AppServicesIndexLazyRoute
  '/traces': typeof AppTracesIndexLazyRoute
  '/infrastructure/containers/$container': typeof AppInfrastructureContainersContainerLazyRoute
  '/infrastructure/hosts/$host': typeof AppInfrastructureHostsHostLazyRoute
  '/monitors/$monitorId/edit': typeof AppMonitorsMonitorIdEditLazyRoute
  '/saturation/database': typeof AppSaturationDatabaseIndexLazyRoute
  '/saturation/database/query/$queryId': typeof AppSaturationDatabaseQueryQueryIdRoute
  '/saturation/database/instance/$system': typeof AppSaturationDatabaseInstanceSystemLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/_app/ingestion': typeof AppIngestionRoute
  '/_app/cloud': typeof AppCloudLazyRoute
  '/_app/device': typeof AppDeviceLazyRoute
  '/_app/llm': typeof AppLlmLazyRoute
  '/_app/metrics': typeof AppMetricsLazyRoute
  '/_app/overview': typeof AppOverviewLazyRoute
  '/_app/settings': typeof AppSettingsLazyRoute
  '/_app/alerts/new': typeof AppAlertsNewRoute
  '/_app/logs/patterns': typeof AppLogsPatternsRoute
  '/_app/logs/transactions': typeof AppLogsTransactionsRoute
  '/_app/services/map': typeof AppServicesMapRoute
  '/_app/traces/$traceId': typeof AppTracesTraceIdRoute
  '/_app/dashboards/$pageId': typeof AppDashboardsPageIdLazyRoute
  '/_app/errors/$groupId': typeof AppErrorsGroupIdLazyRoute
  '/_app/monitors/$monitorId': typeof AppMonitorsMonitorIdLazyRouteWithChildren
  '/_app/monitors/new': typeof AppMonitorsNewLazyRoute
  '/_app/monitors/notifications': typeof AppMonitorsNotificationsLazyRoute
  '/_app/saturation/kafka': typeof AppSaturationKafkaLazyRoute
  '/_app/services/$serviceName': typeof AppServicesServiceNameLazyRoute
  '/_app/dashboards/': typeof AppDashboardsIndexLazyRoute
  '/_app/errors/': typeof AppErrorsIndexLazyRoute
  '/_app/infrastructure/': typeof AppInfrastructureIndexLazyRoute
  '/_app/logs/': typeof AppLogsIndexLazyRoute
  '/_app/monitors/': typeof AppMonitorsIndexLazyRoute
  '/_app/saturation/': typeof AppSaturationIndexLazyRoute
  '/_app/services/': typeof AppServicesIndexLazyRoute
  '/_app/traces/': typeof AppTracesIndexLazyRoute
  '/_app/infrastructure/containers/$container': typeof AppInfrastructureContainersContainerLazyRoute
  '/_app/infrastructure/hosts/$host': typeof AppInfrastructureHostsHostLazyRoute
  '/_app/monitors/$monitorId/edit': typeof AppMonitorsMonitorIdEditLazyRoute
  '/_app/saturation/database/': typeof AppSaturationDatabaseIndexLazyRoute
  '/_app/saturation/database/query/$queryId': typeof AppSaturationDatabaseQueryQueryIdRoute
  '/_app/saturation/database/instance/$system': typeof AppSaturationDatabaseInstanceSystemLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/product'
    | '/reset-password'
    | '/signup'
    | '/welcome'
    | '/ingestion'
    | '/cloud'
    | '/device'
    | '/llm'
    | '/metrics'
    | '/overview'
    | '/settings'
    | '/alerts/new'
    | '/logs/patterns'
    | '/logs/transactions'
    | '/services/map'
    | '/traces/$traceId'
    | '/dashboards/$pageId'
    | '/errors/$groupId'
    | '/monitors/$monitorId'
    | '/monitors/new'
    | '/monitors/notifications'
    | '/saturation/kafka'
    | '/services/$serviceName'
    | '/dashboards/'
    | '/errors/'
    | '/infrastructure/'
    | '/logs/'
    | '/monitors/'
    | '/saturation/'
    | '/services/'
    | '/traces/'
    | '/infrastructure/containers/$container'
    | '/infrastructure/hosts/$host'
    | '/monitors/$monitorId/edit'
    | '/saturation/database/'
    | '/saturation/database/query/$queryId'
    | '/saturation/database/instance/$system'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/product'
    | '/reset-password'
    | '/signup'
    | '/welcome'
    | '/ingestion'
    | '/cloud'
    | '/device'
    | '/llm'
    | '/metrics'
    | '/overview'
    | '/settings'
    | '/alerts/new'
    | '/logs/patterns'
    | '/logs/transactions'
    | '/services/map'
    | '/traces/$traceId'
    | '/dashboards/$pageId'
    | '/errors/$groupId'
    | '/monitors/$monitorId'
    | '/monitors/new'
    | '/monitors/notifications'
    | '/saturation/kafka'
    | '/services/$serviceName'
    | '/dashboards'
    | '/errors'
    | '/infrastructure'
    | '/logs'
    | '/monitors'
    | '/saturation'
    | '/services'
    | '/traces'
    | '/infrastructure/containers/$container'
    | '/infrastructure/hosts/$host'
    | '/monitors/$monitorId/edit'
    | '/saturation/database'
    | '/saturation/database/query/$queryId'
    | '/saturation/database/instance/$system'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/product'
    | '/reset-password'
    | '/signup'
    | '/welcome'
    | '/_app/ingestion'
    | '/_app/cloud'
    | '/_app/device'
    | '/_app/llm'
    | '/_app/metrics'
    | '/_app/overview'
    | '/_app/settings'
    | '/_app/alerts/new'
    | '/_app/logs/patterns'
    | '/_app/logs/transactions'
    | '/_app/services/map'
    | '/_app/traces/$traceId'
    | '/_app/dashboards/$pageId'
    | '/_app/errors/$groupId'
    | '/_app/monitors/$monitorId'
    | '/_app/monitors/new'
    | '/_app/monitors/notifications'
    | '/_app/saturation/kafka'
    | '/_app/services/$serviceName'
    | '/_app/dashboards/'
    | '/_app/errors/'
    | '/_app/infrastructure/'
    | '/_app/logs/'
    | '/_app/monitors/'
    | '/_app/saturation/'
    | '/_app/services/'
    | '/_app/traces/'
    | '/_app/infrastructure/containers/$container'
    | '/_app/infrastructure/hosts/$host'
    | '/_app/monitors/$monitorId/edit'
    | '/_app/saturation/database/'
    | '/_app/saturation/database/query/$queryId'
    | '/_app/saturation/database/instance/$system'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ProductRoute: typeof ProductRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metrics': {
      id: '/_app/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AppMetricsLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/llm': {
      id: '/_app/llm'
      path: '/llm'
      fullPath: '/llm'
      preLoaderRoute: typeof AppLlmLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/device': {
      id: '/_app/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof AppDeviceLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cloud': {
      id: '/_app/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof AppCloudLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingestion': {
      id: '/_app/ingestion'
      path: '/ingestion'
      fullPath: '/ingestion'
      preLoaderRoute: typeof AppIngestionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/traces/': {
      id: '/_app/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof AppTracesIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/': {
      id: '/_app/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AppServicesIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saturation/': {
      id: '/_app/saturation/'
      path: '/saturation'
      fullPath: '/saturation/'
      preLoaderRoute: typeof AppSaturationIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitors/': {
      id: '/_app/monitors/'
      path: '/monitors'
      fullPath: '/monitors/'
      preLoaderRoute: typeof AppMonitorsIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs/': {
      id: '/_app/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof AppLogsIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/infrastructure/': {
      id: '/_app/infrastructure/'
      path: '/infrastructure'
      fullPath: '/infrastructure/'
      preLoaderRoute: typeof AppInfrastructureIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/errors/': {
      id: '/_app/errors/'
      path: '/errors'
      fullPath: '/errors/'
      preLoaderRoute: typeof AppErrorsIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboards/': {
      id: '/_app/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof AppDashboardsIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/$serviceName': {
      id: '/_app/services/$serviceName'
      path: '/services/$serviceName'
      fullPath: '/services/$serviceName'
      preLoaderRoute: typeof AppServicesServiceNameLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saturation/kafka': {
      id: '/_app/saturation/kafka'
      path: '/saturation/kafka'
      fullPath: '/saturation/kafka'
      preLoaderRoute: typeof AppSaturationKafkaLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitors/notifications': {
      id: '/_app/monitors/notifications'
      path: '/monitors/notifications'
      fullPath: '/monitors/notifications'
      preLoaderRoute: typeof AppMonitorsNotificationsLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitors/new': {
      id: '/_app/monitors/new'
      path: '/monitors/new'
      fullPath: '/monitors/new'
      preLoaderRoute: typeof AppMonitorsNewLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitors/$monitorId': {
      id: '/_app/monitors/$monitorId'
      path: '/monitors/$monitorId'
      fullPath: '/monitors/$monitorId'
      preLoaderRoute: typeof AppMonitorsMonitorIdLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/errors/$groupId': {
      id: '/_app/errors/$groupId'
      path: '/errors/$groupId'
      fullPath: '/errors/$groupId'
      preLoaderRoute: typeof AppErrorsGroupIdLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboards/$pageId': {
      id: '/_app/dashboards/$pageId'
      path: '/dashboards/$pageId'
      fullPath: '/dashboards/$pageId'
      preLoaderRoute: typeof AppDashboardsPageIdLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/traces/$traceId': {
      id: '/_app/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof AppTracesTraceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/map': {
      id: '/_app/services/map'
      path: '/services/map'
      fullPath: '/services/map'
      preLoaderRoute: typeof AppServicesMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs/transactions': {
      id: '/_app/logs/transactions'
      path: '/logs/transactions'
      fullPath: '/logs/transactions'
      preLoaderRoute: typeof AppLogsTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs/patterns': {
      id: '/_app/logs/patterns'
      path: '/logs/patterns'
      fullPath: '/logs/patterns'
      preLoaderRoute: typeof AppLogsPatternsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts/new': {
      id: '/_app/alerts/new'
      path: '/alerts/new'
      fullPath: '/alerts/new'
      preLoaderRoute: typeof AppAlertsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saturation/database/': {
      id: '/_app/saturation/database/'
      path: '/saturation/database'
      fullPath: '/saturation/database/'
      preLoaderRoute: typeof AppSaturationDatabaseIndexLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitors/$monitorId/edit': {
      id: '/_app/monitors/$monitorId/edit'
      path: '/edit'
      fullPath: '/monitors/$monitorId/edit'
      preLoaderRoute: typeof AppMonitorsMonitorIdEditLazyRouteImport
      parentRoute: typeof AppMonitorsMonitorIdLazyRoute
    }
    '/_app/infrastructure/hosts/$host': {
      id: '/_app/infrastructure/hosts/$host'
      path: '/infrastructure/hosts/$host'
      fullPath: '/infrastructure/hosts/$host'
      preLoaderRoute: typeof AppInfrastructureHostsHostLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/infrastructure/containers/$container': {
      id: '/_app/infrastructure/containers/$container'
      path: '/infrastructure/containers/$container'
      fullPath: '/infrastructure/containers/$container'
      preLoaderRoute: typeof AppInfrastructureContainersContainerLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saturation/database/instance/$system': {
      id: '/_app/saturation/database/instance/$system'
      path: '/saturation/database/instance/$system'
      fullPath: '/saturation/database/instance/$system'
      preLoaderRoute: typeof AppSaturationDatabaseInstanceSystemLazyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saturation/database/query/$queryId': {
      id: '/_app/saturation/database/query/$queryId'
      path: '/saturation/database/query/$queryId'
      fullPath: '/saturation/database/query/$queryId'
      preLoaderRoute: typeof AppSaturationDatabaseQueryQueryIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppMonitorsMonitorIdLazyRouteChildren {
  AppMonitorsMonitorIdEditLazyRoute: typeof AppMonitorsMonitorIdEditLazyRoute
}

const AppMonitorsMonitorIdLazyRouteChildren: AppMonitorsMonitorIdLazyRouteChildren =
  {
    AppMonitorsMonitorIdEditLazyRoute: AppMonitorsMonitorIdEditLazyRoute,
  }

const AppMonitorsMonitorIdLazyRouteWithChildren =
  AppMonitorsMonitorIdLazyRoute._addFileChildren(
    AppMonitorsMonitorIdLazyRouteChildren,
  )

interface AppRouteChildren {
  AppIngestionRoute: typeof AppIngestionRoute
  AppCloudLazyRoute: typeof AppCloudLazyRoute
  AppDeviceLazyRoute: typeof AppDeviceLazyRoute
  AppLlmLazyRoute: typeof AppLlmLazyRoute
  AppMetricsLazyRoute: typeof AppMetricsLazyRoute
  AppOverviewLazyRoute: typeof AppOverviewLazyRoute
  AppSettingsLazyRoute: typeof AppSettingsLazyRoute
  AppAlertsNewRoute: typeof AppAlertsNewRoute
  AppLogsPatternsRoute: typeof AppLogsPatternsRoute
  AppLogsTransactionsRoute: typeof AppLogsTransactionsRoute
  AppServicesMapRoute: typeof AppServicesMapRoute
  AppTracesTraceIdRoute: typeof AppTracesTraceIdRoute
  AppDashboardsPageIdLazyRoute: typeof AppDashboardsPageIdLazyRoute
  AppErrorsGroupIdLazyRoute: typeof AppErrorsGroupIdLazyRoute
  AppMonitorsMonitorIdLazyRoute: typeof AppMonitorsMonitorIdLazyRouteWithChildren
  AppMonitorsNewLazyRoute: typeof AppMonitorsNewLazyRoute
  AppMonitorsNotificationsLazyRoute: typeof AppMonitorsNotificationsLazyRoute
  AppSaturationKafkaLazyRoute: typeof AppSaturationKafkaLazyRoute
  AppServicesServiceNameLazyRoute: typeof AppServicesServiceNameLazyRoute
  AppDashboardsIndexLazyRoute: typeof AppDashboardsIndexLazyRoute
  AppErrorsIndexLazyRoute: typeof AppErrorsIndexLazyRoute
  AppInfrastructureIndexLazyRoute: typeof AppInfrastructureIndexLazyRoute
  AppLogsIndexLazyRoute: typeof AppLogsIndexLazyRoute
  AppMonitorsIndexLazyRoute: typeof AppMonitorsIndexLazyRoute
  AppSaturationIndexLazyRoute: typeof AppSaturationIndexLazyRoute
  AppServicesIndexLazyRoute: typeof AppServicesIndexLazyRoute
  AppTracesIndexLazyRoute: typeof AppTracesIndexLazyRoute
  AppInfrastructureContainersContainerLazyRoute: typeof AppInfrastructureContainersContainerLazyRoute
  AppInfrastructureHostsHostLazyRoute: typeof AppInfrastructureHostsHostLazyRoute
  AppSaturationDatabaseIndexLazyRoute: typeof AppSaturationDatabaseIndexLazyRoute
  AppSaturationDatabaseQueryQueryIdRoute: typeof AppSaturationDatabaseQueryQueryIdRoute
  AppSaturationDatabaseInstanceSystemLazyRoute: typeof AppSaturationDatabaseInstanceSystemLazyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIngestionRoute: AppIngestionRoute,
  AppCloudLazyRoute: AppCloudLazyRoute,
  AppDeviceLazyRoute: AppDeviceLazyRoute,
  AppLlmLazyRoute: AppLlmLazyRoute,
  AppMetricsLazyRoute: AppMetricsLazyRoute,
  AppOverviewLazyRoute: AppOverviewLazyRoute,
  AppSettingsLazyRoute: AppSettingsLazyRoute,
  AppAlertsNewRoute: AppAlertsNewRoute,
  AppLogsPatternsRoute: AppLogsPatternsRoute,
  AppLogsTransactionsRoute: AppLogsTransactionsRoute,
  AppServicesMapRoute: AppServicesMapRoute,
  AppTracesTraceIdRoute: AppTracesTraceIdRoute,
  AppDashboardsPageIdLazyRoute: AppDashboardsPageIdLazyRoute,
  AppErrorsGroupIdLazyRoute: AppErrorsGroupIdLazyRoute,
  AppMonitorsMonitorIdLazyRoute: AppMonitorsMonitorIdLazyRouteWithChildren,
  AppMonitorsNewLazyRoute: AppMonitorsNewLazyRoute,
  AppMonitorsNotificationsLazyRoute: AppMonitorsNotificationsLazyRoute,
  AppSaturationKafkaLazyRoute: AppSaturationKafkaLazyRoute,
  AppServicesServiceNameLazyRoute: AppServicesServiceNameLazyRoute,
  AppDashboardsIndexLazyRoute: AppDashboardsIndexLazyRoute,
  AppErrorsIndexLazyRoute: AppErrorsIndexLazyRoute,
  AppInfrastructureIndexLazyRoute: AppInfrastructureIndexLazyRoute,
  AppLogsIndexLazyRoute: AppLogsIndexLazyRoute,
  AppMonitorsIndexLazyRoute: AppMonitorsIndexLazyRoute,
  AppSaturationIndexLazyRoute: AppSaturationIndexLazyRoute,
  AppServicesIndexLazyRoute: AppServicesIndexLazyRoute,
  AppTracesIndexLazyRoute: AppTracesIndexLazyRoute,
  AppInfrastructureContainersContainerLazyRoute:
    AppInfrastructureContainersContainerLazyRoute,
  AppInfrastructureHostsHostLazyRoute: AppInfrastructureHostsHostLazyRoute,
  AppSaturationDatabaseIndexLazyRoute: AppSaturationDatabaseIndexLazyRoute,
  AppSaturationDatabaseQueryQueryIdRoute:
    AppSaturationDatabaseQueryQueryIdRoute,
  AppSaturationDatabaseInstanceSystemLazyRoute:
    AppSaturationDatabaseInstanceSystemLazyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ProductRoute: ProductRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
