/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProductRouteImport } from './routes/product'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppMetricsRouteImport } from './routes/_app/metrics'
import { Route as AppLlmRouteImport } from './routes/_app/llm'
import { Route as AppIngestionRouteImport } from './routes/_app/ingestion'
import { Route as AppDeviceRouteImport } from './routes/_app/device'
import { Route as AppTracesIndexRouteImport } from './routes/_app/traces/index'
import { Route as AppServicesIndexRouteImport } from './routes/_app/services/index'
import { Route as AppSaturationIndexRouteImport } from './routes/_app/saturation/index'
import { Route as AppMonitorsIndexRouteImport } from './routes/_app/monitors/index'
import { Route as AppLogsIndexRouteImport } from './routes/_app/logs/index'
import { Route as AppInfrastructureIndexRouteImport } from './routes/_app/infrastructure/index'
import { Route as AppErrorsIndexRouteImport } from './routes/_app/errors/index'
import { Route as AppDashboardsIndexRouteImport } from './routes/_app/dashboards/index'
import { Route as AppTracesTraceIdRouteImport } from './routes/_app/traces/$traceId'
import { Route as AppServicesMapRouteImport } from './routes/_app/services/map'
import { Route as AppServicesServiceNameRouteImport } from './routes/_app/services/$serviceName'
import { Route as AppSaturationKafkaRouteImport } from './routes/_app/saturation/kafka'
import { Route as AppMonitorsNotificationsRouteImport } from './routes/_app/monitors/notifications'
import { Route as AppMonitorsNewRouteImport } from './routes/_app/monitors/new'
import { Route as AppMonitorsMonitorIdRouteImport } from './routes/_app/monitors/$monitorId'
import { Route as AppLogsTransactionsRouteImport } from './routes/_app/logs/transactions'
import { Route as AppLogsPatternsRouteImport } from './routes/_app/logs/patterns'
import { Route as AppErrorsGroupIdRouteImport } from './routes/_app/errors/$groupId'
import { Route as AppDashboardsPageIdRouteImport } from './routes/_app/dashboards/$pageId'
import { Route as AppAlertsNewRouteImport } from './routes/_app/alerts.new'
import { Route as AppSaturationDatabaseIndexRouteImport } from './routes/_app/saturation/database/index'
import { Route as AppMonitorsMonitorIdEditRouteImport } from './routes/_app/monitors/$monitorId/edit'
import { Route as AppInfrastructureHostsHostRouteImport } from './routes/_app/infrastructure/hosts/$host'
import { Route as AppInfrastructureContainersContainerRouteImport } from './routes/_app/infrastructure/containers/$container'
import { Route as AppSaturationDatabaseQueryQueryIdRouteImport } from './routes/_app/saturation/database/query/$queryId'
import { Route as AppSaturationDatabaseInstanceSystemRouteImport } from './routes/_app/saturation/database/instance/$system'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppMetricsRoute = AppMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AppRoute,
} as any)
const AppLlmRoute = AppLlmRouteImport.update({
  id: '/llm',
  path: '/llm',
  getParentRoute: () => AppRoute,
} as any)
const AppIngestionRoute = AppIngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => AppRoute,
} as any)
const AppDeviceRoute = AppDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => AppRoute,
} as any)
const AppTracesIndexRoute = AppTracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesIndexRoute = AppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AppRoute,
} as any)
const AppSaturationIndexRoute = AppSaturationIndexRouteImport.update({
  id: '/saturation/',
  path: '/saturation/',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitorsIndexRoute = AppMonitorsIndexRouteImport.update({
  id: '/monitors/',
  path: '/monitors/',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsIndexRoute = AppLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AppRoute,
} as any)
const AppInfrastructureIndexRoute = AppInfrastructureIndexRouteImport.update({
  id: '/infrastructure/',
  path: '/infrastructure/',
  getParentRoute: () => AppRoute,
} as any)
const AppErrorsIndexRoute = AppErrorsIndexRouteImport.update({
  id: '/errors/',
  path: '/errors/',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardsIndexRoute = AppDashboardsIndexRouteImport.update({
  id: '/dashboards/',
  path: '/dashboards/',
  getParentRoute: () => AppRoute,
} as any)
const AppTracesTraceIdRoute = AppTracesTraceIdRouteImport.update({
  id: '/traces/$traceId',
  path: '/traces/$traceId',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesMapRoute = AppServicesMapRouteImport.update({
  id: '/services/map',
  path: '/services/map',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesServiceNameRoute = AppServicesServiceNameRouteImport.update({
  id: '/services/$serviceName',
  path: '/services/$serviceName',
  getParentRoute: () => AppRoute,
} as any)
const AppSaturationKafkaRoute = AppSaturationKafkaRouteImport.update({
  id: '/saturation/kafka',
  path: '/saturation/kafka',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitorsNotificationsRoute =
  AppMonitorsNotificationsRouteImport.update({
    id: '/monitors/notifications',
    path: '/monitors/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppMonitorsNewRoute = AppMonitorsNewRouteImport.update({
  id: '/monitors/new',
  path: '/monitors/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMonitorsMonitorIdRoute = AppMonitorsMonitorIdRouteImport.update({
  id: '/monitors/$monitorId',
  path: '/monitors/$monitorId',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsTransactionsRoute = AppLogsTransactionsRouteImport.update({
  id: '/logs/transactions',
  path: '/logs/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsPatternsRoute = AppLogsPatternsRouteImport.update({
  id: '/logs/patterns',
  path: '/logs/patterns',
  getParentRoute: () => AppRoute,
} as any)
const AppErrorsGroupIdRoute = AppErrorsGroupIdRouteImport.update({
  id: '/errors/$groupId',
  path: '/errors/$groupId',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardsPageIdRoute = AppDashboardsPageIdRouteImport.update({
  id: '/dashboards/$pageId',
  path: '/dashboards/$pageId',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsNewRoute = AppAlertsNewRouteImport.update({
  id: '/alerts/new',
  path: '/alerts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSaturationDatabaseIndexRoute =
  AppSaturationDatabaseIndexRouteImport.update({
    id: '/saturation/database/',
    path: '/saturation/database/',
    getParentRoute: () => AppRoute,
  } as any)
const AppMonitorsMonitorIdEditRoute =
  AppMonitorsMonitorIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppMonitorsMonitorIdRoute,
  } as any)
const AppInfrastructureHostsHostRoute =
  AppInfrastructureHostsHostRouteImport.update({
    id: '/infrastructure/hosts/$host',
    path: '/infrastructure/hosts/$host',
    getParentRoute: () => AppRoute,
  } as any)
const AppInfrastructureContainersContainerRoute =
  AppInfrastructureContainersContainerRouteImport.update({
    id: '/infrastructure/containers/$container',
    path: '/infrastructure/containers/$container',
    getParentRoute: () => AppRoute,
  } as any)
const AppSaturationDatabaseQueryQueryIdRoute =
  AppSaturationDatabaseQueryQueryIdRouteImport.update({
    id: '/saturation/database/query/$queryId',
    path: '/saturation/database/query/$queryId',
    getParentRoute: () => AppRoute,
  } as any)
const AppSaturationDatabaseInstanceSystemRoute =
  AppSaturationDatabaseInstanceSystemRouteImport.update({
    id: '/saturation/database/instance/$system',
    path: '/saturation/database/instance/$system',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/product': typeof ProductRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/device': typeof AppDeviceRoute
  '/ingestion': typeof AppIngestionRoute
  '/llm': typeof AppLlmRoute
  '/metrics': typeof AppMetricsRoute
  '/overview': typeof AppOverviewRoute
  '/settings': typeof AppSettingsRoute
  '/alerts/new': typeof AppAlertsNewRoute
  '/dashboards/$pageId': typeof AppDashboardsPageIdRoute
  '/errors/$groupId': typeof AppErrorsGroupIdRoute
  '/logs/patterns': typeof AppLogsPatternsRoute
  '/logs/transactions': typeof AppLogsTransactionsRoute
  '/monitors/$monitorId': typeof AppMonitorsMonitorIdRouteWithChildren
  '/monitors/new': typeof AppMonitorsNewRoute
  '/monitors/notifications': typeof AppMonitorsNotificationsRoute
  '/saturation/kafka': typeof AppSaturationKafkaRoute
  '/services/$serviceName': typeof AppServicesServiceNameRoute
  '/services/map': typeof AppServicesMapRoute
  '/traces/$traceId': typeof AppTracesTraceIdRoute
  '/dashboards/': typeof AppDashboardsIndexRoute
  '/errors/': typeof AppErrorsIndexRoute
  '/infrastructure/': typeof AppInfrastructureIndexRoute
  '/logs/': typeof AppLogsIndexRoute
  '/monitors/': typeof AppMonitorsIndexRoute
  '/saturation/': typeof AppSaturationIndexRoute
  '/services/': typeof AppServicesIndexRoute
  '/traces/': typeof AppTracesIndexRoute
  '/infrastructure/containers/$container': typeof AppInfrastructureContainersContainerRoute
  '/infrastructure/hosts/$host': typeof AppInfrastructureHostsHostRoute
  '/monitors/$monitorId/edit': typeof AppMonitorsMonitorIdEditRoute
  '/saturation/database/': typeof AppSaturationDatabaseIndexRoute
  '/saturation/database/instance/$system': typeof AppSaturationDatabaseInstanceSystemRoute
  '/saturation/database/query/$queryId': typeof AppSaturationDatabaseQueryQueryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/product': typeof ProductRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/device': typeof AppDeviceRoute
  '/ingestion': typeof AppIngestionRoute
  '/llm': typeof AppLlmRoute
  '/metrics': typeof AppMetricsRoute
  '/overview': typeof AppOverviewRoute
  '/settings': typeof AppSettingsRoute
  '/alerts/new': typeof AppAlertsNewRoute
  '/dashboards/$pageId': typeof AppDashboardsPageIdRoute
  '/errors/$groupId': typeof AppErrorsGroupIdRoute
  '/logs/patterns': typeof AppLogsPatternsRoute
  '/logs/transactions': typeof AppLogsTransactionsRoute
  '/monitors/$monitorId': typeof AppMonitorsMonitorIdRouteWithChildren
  '/monitors/new': typeof AppMonitorsNewRoute
  '/monitors/notifications': typeof AppMonitorsNotificationsRoute
  '/saturation/kafka': typeof AppSaturationKafkaRoute
  '/services/$serviceName': typeof AppServicesServiceNameRoute
  '/services/map': typeof AppServicesMapRoute
  '/traces/$traceId': typeof AppTracesTraceIdRoute
  '/dashboards': typeof AppDashboardsIndexRoute
  '/errors': typeof AppErrorsIndexRoute
  '/infrastructure': typeof AppInfrastructureIndexRoute
  '/logs': typeof AppLogsIndexRoute
  '/monitors': typeof AppMonitorsIndexRoute
  '/saturation': typeof AppSaturationIndexRoute
  '/services': typeof AppServicesIndexRoute
  '/traces': typeof AppTracesIndexRoute
  '/infrastructure/containers/$container': typeof AppInfrastructureContainersContainerRoute
  '/infrastructure/hosts/$host': typeof AppInfrastructureHostsHostRoute
  '/monitors/$monitorId/edit': typeof AppMonitorsMonitorIdEditRoute
  '/saturation/database': typeof AppSaturationDatabaseIndexRoute
  '/saturation/database/instance/$system': typeof AppSaturationDatabaseInstanceSystemRoute
  '/saturation/database/query/$queryId': typeof AppSaturationDatabaseQueryQueryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/product': typeof ProductRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/_app/device': typeof AppDeviceRoute
  '/_app/ingestion': typeof AppIngestionRoute
  '/_app/llm': typeof AppLlmRoute
  '/_app/metrics': typeof AppMetricsRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/alerts/new': typeof AppAlertsNewRoute
  '/_app/dashboards/$pageId': typeof AppDashboardsPageIdRoute
  '/_app/errors/$groupId': typeof AppErrorsGroupIdRoute
  '/_app/logs/patterns': typeof AppLogsPatternsRoute
  '/_app/logs/transactions': typeof AppLogsTransactionsRoute
  '/_app/monitors/$monitorId': typeof AppMonitorsMonitorIdRouteWithChildren
  '/_app/monitors/new': typeof AppMonitorsNewRoute
  '/_app/monitors/notifications': typeof AppMonitorsNotificationsRoute
  '/_app/saturation/kafka': typeof AppSaturationKafkaRoute
  '/_app/services/$serviceName': typeof AppServicesServiceNameRoute
  '/_app/services/map': typeof AppServicesMapRoute
  '/_app/traces/$traceId': typeof AppTracesTraceIdRoute
  '/_app/dashboards/': typeof AppDashboardsIndexRoute
  '/_app/errors/': typeof AppErrorsIndexRoute
  '/_app/infrastructure/': typeof AppInfrastructureIndexRoute
  '/_app/logs/': typeof AppLogsIndexRoute
  '/_app/monitors/': typeof AppMonitorsIndexRoute
  '/_app/saturation/': typeof AppSaturationIndexRoute
  '/_app/services/': typeof AppServicesIndexRoute
  '/_app/traces/': typeof AppTracesIndexRoute
  '/_app/infrastructure/containers/$container': typeof AppInfrastructureContainersContainerRoute
  '/_app/infrastructure/hosts/$host': typeof AppInfrastructureHostsHostRoute
  '/_app/monitors/$monitorId/edit': typeof AppMonitorsMonitorIdEditRoute
  '/_app/saturation/database/': typeof AppSaturationDatabaseIndexRoute
  '/_app/saturation/database/instance/$system': typeof AppSaturationDatabaseInstanceSystemRoute
  '/_app/saturation/database/query/$queryId': typeof AppSaturationDatabaseQueryQueryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/product'
    | '/signup'
    | '/welcome'
    | '/device'
    | '/ingestion'
    | '/llm'
    | '/metrics'
    | '/overview'
    | '/settings'
    | '/alerts/new'
    | '/dashboards/$pageId'
    | '/errors/$groupId'
    | '/logs/patterns'
    | '/logs/transactions'
    | '/monitors/$monitorId'
    | '/monitors/new'
    | '/monitors/notifications'
    | '/saturation/kafka'
    | '/services/$serviceName'
    | '/services/map'
    | '/traces/$traceId'
    | '/dashboards/'
    | '/errors/'
    | '/infrastructure/'
    | '/logs/'
    | '/monitors/'
    | '/saturation/'
    | '/services/'
    | '/traces/'
    | '/infrastructure/containers/$container'
    | '/infrastructure/hosts/$host'
    | '/monitors/$monitorId/edit'
    | '/saturation/database/'
    | '/saturation/database/instance/$system'
    | '/saturation/database/query/$queryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/product'
    | '/signup'
    | '/welcome'
    | '/device'
    | '/ingestion'
    | '/llm'
    | '/metrics'
    | '/overview'
    | '/settings'
    | '/alerts/new'
    | '/dashboards/$pageId'
    | '/errors/$groupId'
    | '/logs/patterns'
    | '/logs/transactions'
    | '/monitors/$monitorId'
    | '/monitors/new'
    | '/monitors/notifications'
    | '/saturation/kafka'
    | '/services/$serviceName'
    | '/services/map'
    | '/traces/$traceId'
    | '/dashboards'
    | '/errors'
    | '/infrastructure'
    | '/logs'
    | '/monitors'
    | '/saturation'
    | '/services'
    | '/traces'
    | '/infrastructure/containers/$container'
    | '/infrastructure/hosts/$host'
    | '/monitors/$monitorId/edit'
    | '/saturation/database'
    | '/saturation/database/instance/$system'
    | '/saturation/database/query/$queryId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/product'
    | '/signup'
    | '/welcome'
    | '/_app/device'
    | '/_app/ingestion'
    | '/_app/llm'
    | '/_app/metrics'
    | '/_app/overview'
    | '/_app/settings'
    | '/_app/alerts/new'
    | '/_app/dashboards/$pageId'
    | '/_app/errors/$groupId'
    | '/_app/logs/patterns'
    | '/_app/logs/transactions'
    | '/_app/monitors/$monitorId'
    | '/_app/monitors/new'
    | '/_app/monitors/notifications'
    | '/_app/saturation/kafka'
    | '/_app/services/$serviceName'
    | '/_app/services/map'
    | '/_app/traces/$traceId'
    | '/_app/dashboards/'
    | '/_app/errors/'
    | '/_app/infrastructure/'
    | '/_app/logs/'
    | '/_app/monitors/'
    | '/_app/saturation/'
    | '/_app/services/'
    | '/_app/traces/'
    | '/_app/infrastructure/containers/$container'
    | '/_app/infrastructure/hosts/$host'
    | '/_app/monitors/$monitorId/edit'
    | '/_app/saturation/database/'
    | '/_app/saturation/database/instance/$system'
    | '/_app/saturation/database/query/$queryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProductRoute: typeof ProductRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metrics': {
      id: '/_app/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AppMetricsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/llm': {
      id: '/_app/llm'
      path: '/llm'
      fullPath: '/llm'
      preLoaderRoute: typeof AppLlmRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ingestion': {
      id: '/_app/ingestion'
      path: '/ingestion'
      fullPath: '/ingestion'
      preLoaderRoute: typeof AppIngestionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/device': {
      id: '/_app/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof AppDeviceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/traces/': {
      id: '/_app/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof AppTracesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/': {
      id: '/_app/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AppServicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saturation/': {
      id: '/_app/saturation/'
      path: '/saturation'
      fullPath: '/saturation/'
      preLoaderRoute: typeof AppSaturationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitors/': {
      id: '/_app/monitors/'
      path: '/monitors'
      fullPath: '/monitors/'
      preLoaderRoute: typeof AppMonitorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs/': {
      id: '/_app/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof AppLogsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/infrastructure/': {
      id: '/_app/infrastructure/'
      path: '/infrastructure'
      fullPath: '/infrastructure/'
      preLoaderRoute: typeof AppInfrastructureIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/errors/': {
      id: '/_app/errors/'
      path: '/errors'
      fullPath: '/errors/'
      preLoaderRoute: typeof AppErrorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboards/': {
      id: '/_app/dashboards/'
      path: '/dashboards'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof AppDashboardsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/traces/$traceId': {
      id: '/_app/traces/$traceId'
      path: '/traces/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof AppTracesTraceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/map': {
      id: '/_app/services/map'
      path: '/services/map'
      fullPath: '/services/map'
      preLoaderRoute: typeof AppServicesMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/services/$serviceName': {
      id: '/_app/services/$serviceName'
      path: '/services/$serviceName'
      fullPath: '/services/$serviceName'
      preLoaderRoute: typeof AppServicesServiceNameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saturation/kafka': {
      id: '/_app/saturation/kafka'
      path: '/saturation/kafka'
      fullPath: '/saturation/kafka'
      preLoaderRoute: typeof AppSaturationKafkaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitors/notifications': {
      id: '/_app/monitors/notifications'
      path: '/monitors/notifications'
      fullPath: '/monitors/notifications'
      preLoaderRoute: typeof AppMonitorsNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitors/new': {
      id: '/_app/monitors/new'
      path: '/monitors/new'
      fullPath: '/monitors/new'
      preLoaderRoute: typeof AppMonitorsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitors/$monitorId': {
      id: '/_app/monitors/$monitorId'
      path: '/monitors/$monitorId'
      fullPath: '/monitors/$monitorId'
      preLoaderRoute: typeof AppMonitorsMonitorIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs/transactions': {
      id: '/_app/logs/transactions'
      path: '/logs/transactions'
      fullPath: '/logs/transactions'
      preLoaderRoute: typeof AppLogsTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs/patterns': {
      id: '/_app/logs/patterns'
      path: '/logs/patterns'
      fullPath: '/logs/patterns'
      preLoaderRoute: typeof AppLogsPatternsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/errors/$groupId': {
      id: '/_app/errors/$groupId'
      path: '/errors/$groupId'
      fullPath: '/errors/$groupId'
      preLoaderRoute: typeof AppErrorsGroupIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboards/$pageId': {
      id: '/_app/dashboards/$pageId'
      path: '/dashboards/$pageId'
      fullPath: '/dashboards/$pageId'
      preLoaderRoute: typeof AppDashboardsPageIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alerts/new': {
      id: '/_app/alerts/new'
      path: '/alerts/new'
      fullPath: '/alerts/new'
      preLoaderRoute: typeof AppAlertsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saturation/database/': {
      id: '/_app/saturation/database/'
      path: '/saturation/database'
      fullPath: '/saturation/database/'
      preLoaderRoute: typeof AppSaturationDatabaseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/monitors/$monitorId/edit': {
      id: '/_app/monitors/$monitorId/edit'
      path: '/edit'
      fullPath: '/monitors/$monitorId/edit'
      preLoaderRoute: typeof AppMonitorsMonitorIdEditRouteImport
      parentRoute: typeof AppMonitorsMonitorIdRoute
    }
    '/_app/infrastructure/hosts/$host': {
      id: '/_app/infrastructure/hosts/$host'
      path: '/infrastructure/hosts/$host'
      fullPath: '/infrastructure/hosts/$host'
      preLoaderRoute: typeof AppInfrastructureHostsHostRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/infrastructure/containers/$container': {
      id: '/_app/infrastructure/containers/$container'
      path: '/infrastructure/containers/$container'
      fullPath: '/infrastructure/containers/$container'
      preLoaderRoute: typeof AppInfrastructureContainersContainerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saturation/database/query/$queryId': {
      id: '/_app/saturation/database/query/$queryId'
      path: '/saturation/database/query/$queryId'
      fullPath: '/saturation/database/query/$queryId'
      preLoaderRoute: typeof AppSaturationDatabaseQueryQueryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saturation/database/instance/$system': {
      id: '/_app/saturation/database/instance/$system'
      path: '/saturation/database/instance/$system'
      fullPath: '/saturation/database/instance/$system'
      preLoaderRoute: typeof AppSaturationDatabaseInstanceSystemRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppMonitorsMonitorIdRouteChildren {
  AppMonitorsMonitorIdEditRoute: typeof AppMonitorsMonitorIdEditRoute
}

const AppMonitorsMonitorIdRouteChildren: AppMonitorsMonitorIdRouteChildren = {
  AppMonitorsMonitorIdEditRoute: AppMonitorsMonitorIdEditRoute,
}

const AppMonitorsMonitorIdRouteWithChildren =
  AppMonitorsMonitorIdRoute._addFileChildren(AppMonitorsMonitorIdRouteChildren)

interface AppRouteChildren {
  AppDeviceRoute: typeof AppDeviceRoute
  AppIngestionRoute: typeof AppIngestionRoute
  AppLlmRoute: typeof AppLlmRoute
  AppMetricsRoute: typeof AppMetricsRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAlertsNewRoute: typeof AppAlertsNewRoute
  AppDashboardsPageIdRoute: typeof AppDashboardsPageIdRoute
  AppErrorsGroupIdRoute: typeof AppErrorsGroupIdRoute
  AppLogsPatternsRoute: typeof AppLogsPatternsRoute
  AppLogsTransactionsRoute: typeof AppLogsTransactionsRoute
  AppMonitorsMonitorIdRoute: typeof AppMonitorsMonitorIdRouteWithChildren
  AppMonitorsNewRoute: typeof AppMonitorsNewRoute
  AppMonitorsNotificationsRoute: typeof AppMonitorsNotificationsRoute
  AppSaturationKafkaRoute: typeof AppSaturationKafkaRoute
  AppServicesServiceNameRoute: typeof AppServicesServiceNameRoute
  AppServicesMapRoute: typeof AppServicesMapRoute
  AppTracesTraceIdRoute: typeof AppTracesTraceIdRoute
  AppDashboardsIndexRoute: typeof AppDashboardsIndexRoute
  AppErrorsIndexRoute: typeof AppErrorsIndexRoute
  AppInfrastructureIndexRoute: typeof AppInfrastructureIndexRoute
  AppLogsIndexRoute: typeof AppLogsIndexRoute
  AppMonitorsIndexRoute: typeof AppMonitorsIndexRoute
  AppSaturationIndexRoute: typeof AppSaturationIndexRoute
  AppServicesIndexRoute: typeof AppServicesIndexRoute
  AppTracesIndexRoute: typeof AppTracesIndexRoute
  AppInfrastructureContainersContainerRoute: typeof AppInfrastructureContainersContainerRoute
  AppInfrastructureHostsHostRoute: typeof AppInfrastructureHostsHostRoute
  AppSaturationDatabaseIndexRoute: typeof AppSaturationDatabaseIndexRoute
  AppSaturationDatabaseInstanceSystemRoute: typeof AppSaturationDatabaseInstanceSystemRoute
  AppSaturationDatabaseQueryQueryIdRoute: typeof AppSaturationDatabaseQueryQueryIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDeviceRoute: AppDeviceRoute,
  AppIngestionRoute: AppIngestionRoute,
  AppLlmRoute: AppLlmRoute,
  AppMetricsRoute: AppMetricsRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAlertsNewRoute: AppAlertsNewRoute,
  AppDashboardsPageIdRoute: AppDashboardsPageIdRoute,
  AppErrorsGroupIdRoute: AppErrorsGroupIdRoute,
  AppLogsPatternsRoute: AppLogsPatternsRoute,
  AppLogsTransactionsRoute: AppLogsTransactionsRoute,
  AppMonitorsMonitorIdRoute: AppMonitorsMonitorIdRouteWithChildren,
  AppMonitorsNewRoute: AppMonitorsNewRoute,
  AppMonitorsNotificationsRoute: AppMonitorsNotificationsRoute,
  AppSaturationKafkaRoute: AppSaturationKafkaRoute,
  AppServicesServiceNameRoute: AppServicesServiceNameRoute,
  AppServicesMapRoute: AppServicesMapRoute,
  AppTracesTraceIdRoute: AppTracesTraceIdRoute,
  AppDashboardsIndexRoute: AppDashboardsIndexRoute,
  AppErrorsIndexRoute: AppErrorsIndexRoute,
  AppInfrastructureIndexRoute: AppInfrastructureIndexRoute,
  AppLogsIndexRoute: AppLogsIndexRoute,
  AppMonitorsIndexRoute: AppMonitorsIndexRoute,
  AppSaturationIndexRoute: AppSaturationIndexRoute,
  AppServicesIndexRoute: AppServicesIndexRoute,
  AppTracesIndexRoute: AppTracesIndexRoute,
  AppInfrastructureContainersContainerRoute:
    AppInfrastructureContainersContainerRoute,
  AppInfrastructureHostsHostRoute: AppInfrastructureHostsHostRoute,
  AppSaturationDatabaseIndexRoute: AppSaturationDatabaseIndexRoute,
  AppSaturationDatabaseInstanceSystemRoute:
    AppSaturationDatabaseInstanceSystemRoute,
  AppSaturationDatabaseQueryQueryIdRoute:
    AppSaturationDatabaseQueryQueryIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ProductRoute: ProductRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
