export const ROUTES = {
  login: "/login",
  product: "/product",
  home: "/",
  features: "/features",
  architecture: "/architecture",
  pricing: "/pricing",
  opentelemetry: "/opentelemetry",
  selfHost: "/self-host",
  overview: "/overview",
  service: "/service",
  logs: "/logs",
  traces: "/traces",
  traceDetail: "/traces/$traceId",
  traceCompare: "/traces/compare",
  metrics: "/metrics",
  infrastructure: "/infrastructure",
  errors: "/errors",
  saturation: "/saturation",
  saturationDatastoreDetail: "/saturation/datastores/$system",
  saturationKafkaTopicDetail: "/saturation/kafka/topics/$topic",
  saturationKafkaGroupDetail: "/saturation/kafka/groups/$groupId",
  llmOverview: "/llm/overview",
  llmTraces: "/llm/traces",
  llmGenerations: "/llm/generations",
  llmSessions: "/llm/sessions",
  llmScores: "/llm/scores",
  llmPrompts: "/llm/prompts",
  llmDatasets: "/llm/datasets",
  llmSettings: "/llm/settings",
  settings: "/settings",
  alerts: "/alerts",
  alertRuleNew: "/alerts/rules/new",
  alertRuleDetail: "/alerts/rules/$ruleId",
  alertRuleEdit: "/alerts/rules/$ruleId/edit",
} as const

export type AppRoutePath = (typeof ROUTES)[keyof typeof ROUTES]
