name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  checks:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check

#      - name: Lint
#        run: npm run lint

      - name: Build
        run: npm run build

      - name: Bundle size budgets
        run: npm run ci:budgets

      - name: Bundle Size Diff
        if: github.event_name == 'pull_request'
        uses: preactjs/compressed-size-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          build-script: "build"
          pattern: "./dist/assets/*.{js,css}"
          minimum-change-threshold: 100
